// Code generated by ent, DO NOT EDIT.

package aiconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the aiconfig type in the database.
	Label = "ai_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldConfigKey holds the string denoting the config_key field in the database.
	FieldConfigKey = "config_key"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldTemperature holds the string denoting the temperature field in the database.
	FieldTemperature = "temperature"
	// FieldMaxTokens holds the string denoting the max_tokens field in the database.
	FieldMaxTokens = "max_tokens"
	// FieldTopP holds the string denoting the top_p field in the database.
	FieldTopP = "top_p"
	// FieldFrequencyPenalty holds the string denoting the frequency_penalty field in the database.
	FieldFrequencyPenalty = "frequency_penalty"
	// FieldPresencePenalty holds the string denoting the presence_penalty field in the database.
	FieldPresencePenalty = "presence_penalty"
	// FieldAPIKeyCiphertext holds the string denoting the api_key_ciphertext field in the database.
	FieldAPIKeyCiphertext = "api_key_ciphertext"
	// Table holds the table name of the aiconfig in the database.
	Table = "ai_configs"
)

// Columns holds all SQL columns for aiconfig fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldConfigKey,
	FieldBaseURL,
	FieldModel,
	FieldTemperature,
	FieldMaxTokens,
	FieldTopP,
	FieldFrequencyPenalty,
	FieldPresencePenalty,
	FieldAPIKeyCiphertext,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	BaseURLValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultTemperature holds the default value on creation for the "temperature" field.
	DefaultTemperature float64
	// DefaultMaxTokens holds the default value on creation for the "max_tokens" field.
	DefaultMaxTokens int
	// MaxTokensValidator is a validator for the "max_tokens" field. It is called by the builders before save.
	MaxTokensValidator func(int) error
	// DefaultTopP holds the default value on creation for the "top_p" field.
	DefaultTopP float64
	// DefaultFrequencyPenalty holds the default value on creation for the "frequency_penalty" field.
	DefaultFrequencyPenalty float64
	// DefaultPresencePenalty holds the default value on creation for the "presence_penalty" field.
	DefaultPresencePenalty float64
	// APIKeyCiphertextValidator is a validator for the "api_key_ciphertext" field. It is called by the builders before save.
	APIKeyCiphertextValidator func(string) error
)

// OrderOption defines the ordering options for the AIConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByConfigKey orders the results by the config_key field.
func ByConfigKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigKey, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByTemperature orders the results by the temperature field.
func ByTemperature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemperature, opts...).ToFunc()
}

// ByMaxTokens orders the results by the max_tokens field.
func ByMaxTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxTokens, opts...).ToFunc()
}

// ByTopP orders the results by the top_p field.
func ByTopP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopP, opts...).ToFunc()
}

// ByFrequencyPenalty orders the results by the frequency_penalty field.
func ByFrequencyPenalty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrequencyPenalty, opts...).ToFunc()
}

// ByPresencePenalty orders the results by the presence_penalty field.
func ByPresencePenalty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPresencePenalty, opts...).ToFunc()
}

// ByAPIKeyCiphertext orders the results by the api_key_ciphertext field.
func ByAPIKeyCiphertext(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyCiphertext, opts...).ToFunc()
}
