// Code generated by ent, DO NOT EDIT.

package doclibrarydetail

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the doclibrarydetail type in the database.
	Label = "doc_library_detail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldLibraryID holds the string denoting the library_id field in the database.
	FieldLibraryID = "library_id"
	// EdgeLibrary holds the string denoting the library edge name in mutations.
	EdgeLibrary = "library"
	// Table holds the table name of the doclibrarydetail in the database.
	Table = "doc_library_details"
	// LibraryTable is the table that holds the library relation/edge.
	LibraryTable = "doc_library_details"
	// LibraryInverseTable is the table name for the DocLibrary entity.
	// It exists in this package in order to avoid circular dependency with the "doclibrary" package.
	LibraryInverseTable = "doc_libraries"
	// LibraryColumn is the table column denoting the library relation/edge.
	LibraryColumn = "library_id"
)

// Columns holds all SQL columns for doclibrarydetail fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTitle,
	FieldVersion,
	FieldContent,
	FieldParentID,
	FieldPath,
	FieldURL,
	FieldLanguage,
	FieldLibraryID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
)

// OrderOption defines the ordering options for the DocLibraryDetail queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByParentID orders the results by the parent_id field.
func ByParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentID, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByLibraryID orders the results by the library_id field.
func ByLibraryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLibraryID, opts...).ToFunc()
}

// ByLibraryField orders the results by library field.
func ByLibraryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLibraryStep(), sql.OrderByField(field, opts...))
	}
}
func newLibraryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LibraryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LibraryTable, LibraryColumn),
	)
}
