// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: pkg/plugin/capability/proto/capability.proto

// 通用能力调用协议：宿主与插件共享的通用业务契约。
// 插件通过实现 CapabilityService 暴露任意业务能力（method + JSON 参数透传），
// 宿主无需为具体插件编写业务适配代码。

package capability_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapabilityService_Call_FullMethodName = "/capability.CapabilityService/Call"
)

// CapabilityServiceClient is the client API for CapabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CapabilityServiceClient interface {
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
}

type capabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapabilityServiceClient(cc grpc.ClientConnInterface) CapabilityServiceClient {
	return &capabilityServiceClient{cc}
}

func (c *capabilityServiceClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, CapabilityService_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapabilityServiceServer is the server API for CapabilityService service.
// All implementations must embed UnimplementedCapabilityServiceServer
// for forward compatibility.
type CapabilityServiceServer interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
	mustEmbedUnimplementedCapabilityServiceServer()
}

// UnimplementedCapabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapabilityServiceServer struct{}

func (UnimplementedCapabilityServiceServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedCapabilityServiceServer) mustEmbedUnimplementedCapabilityServiceServer() {}
func (UnimplementedCapabilityServiceServer) testEmbeddedByValue()                           {}

// UnsafeCapabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapabilityServiceServer will
// result in compilation errors.
type UnsafeCapabilityServiceServer interface {
	mustEmbedUnimplementedCapabilityServiceServer()
}

func RegisterCapabilityServiceServer(s grpc.ServiceRegistrar, srv CapabilityServiceServer) {
	// If the following call panics, it indicates UnimplementedCapabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapabilityService_ServiceDesc, srv)
}

func _CapabilityService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapabilityService_ServiceDesc is the grpc.ServiceDesc for CapabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capability.CapabilityService",
	HandlerType: (*CapabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _CapabilityService_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/capability/proto/capability.proto",
}
