// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AlbumsColumns holds the columns for the "albums" table.
	AlbumsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "sort", Type: field.TypeInt, Nullable: true, Default: 0},
	}
	// AlbumsTable holds the schema information for the "albums" table.
	AlbumsTable = &schema.Table{
		Name:       "albums",
		Columns:    AlbumsColumns,
		PrimaryKey: []*schema.Column{AlbumsColumns[0]},
	}
	// AlbumPhotosColumns holds the columns for the "album_photos" table.
	AlbumPhotosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "image_url", Type: field.TypeString},
		{Name: "view_count", Type: field.TypeInt, Default: 0},
		{Name: "album_id", Type: field.TypeInt},
	}
	// AlbumPhotosTable holds the schema information for the "album_photos" table.
	AlbumPhotosTable = &schema.Table{
		Name:       "album_photos",
		Columns:    AlbumPhotosColumns,
		PrimaryKey: []*schema.Column{AlbumPhotosColumns[0]},
	}
	// APIPermsColumns holds the columns for the "api_perms" table.
	APIPermsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "method", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
		{Name: "permission_type", Type: field.TypeString, Default: "private"},
		{Name: "roles", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeString, Default: "active"},
	}
	// APIPermsTable holds the schema information for the "api_perms" table.
	APIPermsTable = &schema.Table{
		Name:       "api_perms",
		Columns:    APIPermsColumns,
		PrimaryKey: []*schema.Column{APIPermsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "apiperms_path_method",
				Unique:  true,
				Columns: []*schema.Column{APIPermsColumns[4], APIPermsColumns[5]},
			},
		},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "post_id", Type: field.TypeInt},
		{Name: "page_id", Type: field.TypeInt},
		{Name: "content", Type: field.TypeString, Size: 1024},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "status", Type: field.TypeInt},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "ip_address", Type: field.TypeString, Size: 45},
		{Name: "ip_location", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "pinned", Type: field.TypeBool, Default: false},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
	}
	// FilesColumns holds the columns for the "files" table.
	FilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "path", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "url", Type: field.TypeString, Size: 1024},
		{Name: "type", Type: field.TypeString},
		{Name: "size", Type: field.TypeString},
	}
	// FilesTable holds the schema information for the "files" table.
	FilesTable = &schema.Table{
		Name:       "files",
		Columns:    FilesColumns,
		PrimaryKey: []*schema.Column{FilesColumns[0]},
	}
	// ModelSchemasColumns holds the columns for the "model_schemas" table.
	ModelSchemasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// ModelSchemasTable holds the schema information for the "model_schemas" table.
	ModelSchemasTable = &schema.Table{
		Name:       "model_schemas",
		Columns:    ModelSchemasColumns,
		PrimaryKey: []*schema.Column{ModelSchemasColumns[0]},
	}
	// Oauth2accessTokensColumns holds the columns for the "oauth2access_tokens" table.
	Oauth2accessTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "access_token", Type: field.TypeString, Size: 255},
		{Name: "refresh_token", Type: field.TypeString, Size: 32},
		{Name: "client_id", Type: field.TypeString, Size: 255},
		{Name: "scope", Type: field.TypeString, Size: 255},
		{Name: "expire_at", Type: field.TypeTime},
	}
	// Oauth2accessTokensTable holds the schema information for the "oauth2access_tokens" table.
	Oauth2accessTokensTable = &schema.Table{
		Name:       "oauth2access_tokens",
		Columns:    Oauth2accessTokensColumns,
		PrimaryKey: []*schema.Column{Oauth2accessTokensColumns[0]},
	}
	// Oauth2codesColumns holds the columns for the "oauth2codes" table.
	Oauth2codesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "code", Type: field.TypeString, Size: 32},
		{Name: "expire_at", Type: field.TypeTime},
		{Name: "client_id", Type: field.TypeString, Size: 255},
		{Name: "redirect_uri", Type: field.TypeString, Size: 255},
		{Name: "scope", Type: field.TypeString, Size: 255},
	}
	// Oauth2codesTable holds the schema information for the "oauth2codes" table.
	Oauth2codesTable = &schema.Table{
		Name:       "oauth2codes",
		Columns:    Oauth2codesColumns,
		PrimaryKey: []*schema.Column{Oauth2codesColumns[0]},
	}
	// Oauth2refreshTokensColumns holds the columns for the "oauth2refresh_tokens" table.
	Oauth2refreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "refresh_token", Type: field.TypeString, Size: 32},
		{Name: "client_id", Type: field.TypeString, Size: 255},
		{Name: "scope", Type: field.TypeString, Size: 255},
		{Name: "expire_at", Type: field.TypeTime},
	}
	// Oauth2refreshTokensTable holds the schema information for the "oauth2refresh_tokens" table.
	Oauth2refreshTokensTable = &schema.Table{
		Name:       "oauth2refresh_tokens",
		Columns:    Oauth2refreshTokensColumns,
		PrimaryKey: []*schema.Column{Oauth2refreshTokensColumns[0]},
	}
	// PagesColumns holds the columns for the "pages" table.
	PagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// PagesTable holds the schema information for the "pages" table.
	PagesTable = &schema.Table{
		Name:       "pages",
		Columns:    PagesColumns,
		PrimaryKey: []*schema.Column{PagesColumns[0]},
	}
	// PayChannelsColumns holds the columns for the "pay_channels" table.
	PayChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "code", Type: field.TypeString, Size: 255},
		{Name: "type", Type: field.TypeString, Size: 255},
		{Name: "config", Type: field.TypeString},
	}
	// PayChannelsTable holds the schema information for the "pay_channels" table.
	PayChannelsTable = &schema.Table{
		Name:       "pay_channels",
		Columns:    PayChannelsColumns,
		PrimaryKey: []*schema.Column{PayChannelsColumns[0]},
	}
	// PayOrdersColumns holds the columns for the "pay_orders" table.
	PayOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "channel_id", Type: field.TypeString},
		{Name: "order_id", Type: field.TypeString},
		{Name: "out_trade_no", Type: field.TypeString},
		{Name: "total_fee", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString},
		{Name: "body", Type: field.TypeString},
		{Name: "notify_url", Type: field.TypeString},
		{Name: "return_url", Type: field.TypeString},
		{Name: "extra", Type: field.TypeString},
		{Name: "pay_url", Type: field.TypeString, Nullable: true},
		{Name: "state", Type: field.TypeString, Default: "1"},
		{Name: "error_msg", Type: field.TypeString, Nullable: true},
		{Name: "raw", Type: field.TypeString, Nullable: true},
	}
	// PayOrdersTable holds the schema information for the "pay_orders" table.
	PayOrdersTable = &schema.Table{
		Name:       "pay_orders",
		Columns:    PayOrdersColumns,
		PrimaryKey: []*schema.Column{PayOrdersColumns[0]},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "alias", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "is_published", Type: field.TypeBool, Default: false},
		{Name: "is_autogen_summary", Type: field.TypeBool, Default: false},
		{Name: "is_visible", Type: field.TypeBool, Default: true},
		{Name: "is_tip_to_top", Type: field.TypeBool, Default: false},
		{Name: "is_allow_comment", Type: field.TypeBool, Default: true},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "view_count", Type: field.TypeInt, Default: 0},
		{Name: "comment_count", Type: field.TypeInt, Default: 0},
		{Name: "cover", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "keywords", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "copyright", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "author", Type: field.TypeString, Default: "匿名作者"},
		{Name: "summary", Type: field.TypeString, Nullable: true, Size: 512},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "key", Type: field.TypeString, Size: 255},
		{Name: "value", Type: field.TypeString, Size: 255},
		{Name: "comment", Type: field.TypeString, Nullable: true, Size: 512},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// StorageStrategiesColumns holds the columns for the "storage_strategies" table.
	StorageStrategiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"local", "s3"}, Default: "local"},
		{Name: "node_id", Type: field.TypeString, Default: ""},
		{Name: "endpoint", Type: field.TypeString, Default: ""},
		{Name: "region", Type: field.TypeString, Default: ""},
		{Name: "bucket", Type: field.TypeString},
		{Name: "access_key", Type: field.TypeString, Default: ""},
		{Name: "secret_key", Type: field.TypeString, Default: ""},
		{Name: "base_path", Type: field.TypeString, Default: ""},
		{Name: "domain", Type: field.TypeString, Default: ""},
		{Name: "master", Type: field.TypeBool, Default: false},
	}
	// StorageStrategiesTable holds the schema information for the "storage_strategies" table.
	StorageStrategiesTable = &schema.Table{
		Name:       "storage_strategies",
		Columns:    StorageStrategiesColumns,
		PrimaryKey: []*schema.Column{StorageStrategiesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "email_verified", Type: field.TypeBool, Default: false},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
		{Name: "phone_number", Type: field.TypeString, Unique: true, Nullable: true, Size: 20},
		{Name: "phone_number_verified", Type: field.TypeBool, Default: false},
		{Name: "password", Type: field.TypeString, Size: 255},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// WebHooksColumns holds the columns for the "web_hooks" table.
	WebHooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "url", Type: field.TypeString, Size: 255},
		{Name: "event", Type: field.TypeString, Size: 255},
	}
	// WebHooksTable holds the schema information for the "web_hooks" table.
	WebHooksTable = &schema.Table{
		Name:       "web_hooks",
		Columns:    WebHooksColumns,
		PrimaryKey: []*schema.Column{WebHooksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AlbumsTable,
		AlbumPhotosTable,
		APIPermsTable,
		CommentsTable,
		FilesTable,
		ModelSchemasTable,
		Oauth2accessTokensTable,
		Oauth2codesTable,
		Oauth2refreshTokensTable,
		PagesTable,
		PayChannelsTable,
		PayOrdersTable,
		PostsTable,
		SettingsTable,
		StorageStrategiesTable,
		UsersTable,
		WebHooksTable,
	}
)

func init() {
}
