// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ModelSchemasColumns holds the columns for the "model_schemas" table.
	ModelSchemasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// ModelSchemasTable holds the schema information for the "model_schemas" table.
	ModelSchemasTable = &schema.Table{
		Name:       "model_schemas",
		Columns:    ModelSchemasColumns,
		PrimaryKey: []*schema.Column{ModelSchemasColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ModelSchemasTable,
		UsersTable,
	}
)

func init() {
}
