// Code generated by ent, DO NOT EDIT.

package friendcirclerule

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the friendcirclerule type in the database.
	Label = "friend_circle_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTitleSelector holds the string denoting the title_selector field in the database.
	FieldTitleSelector = "title_selector"
	// FieldLinkSelector holds the string denoting the link_selector field in the database.
	FieldLinkSelector = "link_selector"
	// FieldCreatedSelector holds the string denoting the created_selector field in the database.
	FieldCreatedSelector = "created_selector"
	// FieldUpdatedSelector holds the string denoting the updated_selector field in the database.
	FieldUpdatedSelector = "updated_selector"
	// Table holds the table name of the friendcirclerule in the database.
	Table = "friend_circle_rules"
)

// Columns holds all SQL columns for friendcirclerule fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldTitleSelector,
	FieldLinkSelector,
	FieldCreatedSelector,
	FieldUpdatedSelector,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the FriendCircleRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTitleSelector orders the results by the title_selector field.
func ByTitleSelector(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleSelector, opts...).ToFunc()
}

// ByLinkSelector orders the results by the link_selector field.
func ByLinkSelector(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkSelector, opts...).ToFunc()
}

// ByCreatedSelector orders the results by the created_selector field.
func ByCreatedSelector(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedSelector, opts...).ToFunc()
}

// ByUpdatedSelector orders the results by the updated_selector field.
func ByUpdatedSelector(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedSelector, opts...).ToFunc()
}
