// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/hoshikuzu/ent/aichatmessage"
	"github.com/shuTwT/hoshikuzu/ent/aichatsession"
	"github.com/shuTwT/hoshikuzu/ent/predicate"
)

// AIChatMessageUpdate is the builder for updating AIChatMessage entities.
type AIChatMessageUpdate struct {
	config
	hooks    []Hook
	mutation *AIChatMessageMutation
}

// Where appends a list predicates to the AIChatMessageUpdate builder.
func (_u *AIChatMessageUpdate) Where(ps ...predicate.AIChatMessage) *AIChatMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AIChatMessageUpdate) SetUpdatedAt(v time.Time) *AIChatMessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AIChatMessageUpdate) SetSessionID(v int) *AIChatMessageUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AIChatMessageUpdate) SetNillableSessionID(v *int) *AIChatMessageUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *AIChatMessageUpdate) SetRole(v aichatmessage.Role) *AIChatMessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *AIChatMessageUpdate) SetNillableRole(v *aichatmessage.Role) *AIChatMessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *AIChatMessageUpdate) SetContent(v string) *AIChatMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *AIChatMessageUpdate) SetNillableContent(v *string) *AIChatMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AIChatMessageUpdate) SetModel(v string) *AIChatMessageUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AIChatMessageUpdate) SetNillableModel(v *string) *AIChatMessageUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *AIChatMessageUpdate) ClearModel() *AIChatMessageUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetSession sets the "session" edge to the AIChatSession entity.
func (_u *AIChatMessageUpdate) SetSession(v *AIChatSession) *AIChatMessageUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the AIChatMessageMutation object of the builder.
func (_u *AIChatMessageUpdate) Mutation() *AIChatMessageMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the AIChatSession entity.
func (_u *AIChatMessageUpdate) ClearSession() *AIChatMessageUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AIChatMessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIChatMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AIChatMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIChatMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AIChatMessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aichatmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIChatMessageUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := aichatmessage.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AIChatMessage.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := aichatmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "AIChatMessage.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := aichatmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "AIChatMessage.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := aichatmessage.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AIChatMessage.model": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AIChatMessage.session"`)
	}
	return nil
}

func (_u *AIChatMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aichatmessage.Table, aichatmessage.Columns, sqlgraph.NewFieldSpec(aichatmessage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aichatmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(aichatmessage.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(aichatmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(aichatmessage.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(aichatmessage.FieldModel, field.TypeString)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aichatmessage.SessionTable,
			Columns: []string{aichatmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aichatsession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aichatmessage.SessionTable,
			Columns: []string{aichatmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aichatsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aichatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AIChatMessageUpdateOne is the builder for updating a single AIChatMessage entity.
type AIChatMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AIChatMessageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AIChatMessageUpdateOne) SetUpdatedAt(v time.Time) *AIChatMessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AIChatMessageUpdateOne) SetSessionID(v int) *AIChatMessageUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AIChatMessageUpdateOne) SetNillableSessionID(v *int) *AIChatMessageUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *AIChatMessageUpdateOne) SetRole(v aichatmessage.Role) *AIChatMessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *AIChatMessageUpdateOne) SetNillableRole(v *aichatmessage.Role) *AIChatMessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *AIChatMessageUpdateOne) SetContent(v string) *AIChatMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *AIChatMessageUpdateOne) SetNillableContent(v *string) *AIChatMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AIChatMessageUpdateOne) SetModel(v string) *AIChatMessageUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AIChatMessageUpdateOne) SetNillableModel(v *string) *AIChatMessageUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *AIChatMessageUpdateOne) ClearModel() *AIChatMessageUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetSession sets the "session" edge to the AIChatSession entity.
func (_u *AIChatMessageUpdateOne) SetSession(v *AIChatSession) *AIChatMessageUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the AIChatMessageMutation object of the builder.
func (_u *AIChatMessageUpdateOne) Mutation() *AIChatMessageMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the AIChatSession entity.
func (_u *AIChatMessageUpdateOne) ClearSession() *AIChatMessageUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the AIChatMessageUpdate builder.
func (_u *AIChatMessageUpdateOne) Where(ps ...predicate.AIChatMessage) *AIChatMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AIChatMessageUpdateOne) Select(field string, fields ...string) *AIChatMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AIChatMessage entity.
func (_u *AIChatMessageUpdateOne) Save(ctx context.Context) (*AIChatMessage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIChatMessageUpdateOne) SaveX(ctx context.Context) *AIChatMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AIChatMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIChatMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AIChatMessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aichatmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIChatMessageUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := aichatmessage.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AIChatMessage.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := aichatmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "AIChatMessage.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := aichatmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "AIChatMessage.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := aichatmessage.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AIChatMessage.model": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AIChatMessage.session"`)
	}
	return nil
}

func (_u *AIChatMessageUpdateOne) sqlSave(ctx context.Context) (_node *AIChatMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aichatmessage.Table, aichatmessage.Columns, sqlgraph.NewFieldSpec(aichatmessage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AIChatMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aichatmessage.FieldID)
		for _, f := range fields {
			if !aichatmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aichatmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aichatmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(aichatmessage.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(aichatmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(aichatmessage.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(aichatmessage.FieldModel, field.TypeString)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aichatmessage.SessionTable,
			Columns: []string{aichatmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aichatsession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aichatmessage.SessionTable,
			Columns: []string{aichatmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aichatsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AIChatMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aichatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
