// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/hoshikuzu/ent/aiconfig"
)

// AIConfig is the model entity for the AIConfig schema.
type AIConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 单例配置标识
	ConfigKey string `json:"config_key,omitempty"`
	// OpenAI 兼容接口基础地址
	BaseURL string `json:"base_url,omitempty"`
	// 默认模型
	Model string `json:"model,omitempty"`
	// 温度
	Temperature float64 `json:"temperature,omitempty"`
	// 最大输出 Token
	MaxTokens int `json:"max_tokens,omitempty"`
	// Top P
	TopP float64 `json:"top_p,omitempty"`
	// 频率惩罚
	FrequencyPenalty float64 `json:"frequency_penalty,omitempty"`
	// 存在惩罚
	PresencePenalty float64 `json:"presence_penalty,omitempty"`
	// AES-GCM 加密后的供应商 API Key
	APIKeyCiphertext string `json:"-"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AIConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aiconfig.FieldTemperature, aiconfig.FieldTopP, aiconfig.FieldFrequencyPenalty, aiconfig.FieldPresencePenalty:
			values[i] = new(sql.NullFloat64)
		case aiconfig.FieldID, aiconfig.FieldMaxTokens:
			values[i] = new(sql.NullInt64)
		case aiconfig.FieldConfigKey, aiconfig.FieldBaseURL, aiconfig.FieldModel, aiconfig.FieldAPIKeyCiphertext:
			values[i] = new(sql.NullString)
		case aiconfig.FieldCreatedAt, aiconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AIConfig fields.
func (_m *AIConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aiconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case aiconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case aiconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case aiconfig.FieldConfigKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_key", values[i])
			} else if value.Valid {
				_m.ConfigKey = value.String
			}
		case aiconfig.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case aiconfig.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case aiconfig.FieldTemperature:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field temperature", values[i])
			} else if value.Valid {
				_m.Temperature = value.Float64
			}
		case aiconfig.FieldMaxTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_tokens", values[i])
			} else if value.Valid {
				_m.MaxTokens = int(value.Int64)
			}
		case aiconfig.FieldTopP:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field top_p", values[i])
			} else if value.Valid {
				_m.TopP = value.Float64
			}
		case aiconfig.FieldFrequencyPenalty:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field frequency_penalty", values[i])
			} else if value.Valid {
				_m.FrequencyPenalty = value.Float64
			}
		case aiconfig.FieldPresencePenalty:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field presence_penalty", values[i])
			} else if value.Valid {
				_m.PresencePenalty = value.Float64
			}
		case aiconfig.FieldAPIKeyCiphertext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_ciphertext", values[i])
			} else if value.Valid {
				_m.APIKeyCiphertext = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AIConfig.
// This includes values selected through modifiers, order, etc.
func (_m *AIConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AIConfig.
// Note that you need to call AIConfig.Unwrap() before calling this method if this AIConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AIConfig) Update() *AIConfigUpdateOne {
	return NewAIConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AIConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AIConfig) Unwrap() *AIConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AIConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AIConfig) String() string {
	var builder strings.Builder
	builder.WriteString("AIConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("config_key=")
	builder.WriteString(_m.ConfigKey)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("temperature=")
	builder.WriteString(fmt.Sprintf("%v", _m.Temperature))
	builder.WriteString(", ")
	builder.WriteString("max_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxTokens))
	builder.WriteString(", ")
	builder.WriteString("top_p=")
	builder.WriteString(fmt.Sprintf("%v", _m.TopP))
	builder.WriteString(", ")
	builder.WriteString("frequency_penalty=")
	builder.WriteString(fmt.Sprintf("%v", _m.FrequencyPenalty))
	builder.WriteString(", ")
	builder.WriteString("presence_penalty=")
	builder.WriteString(fmt.Sprintf("%v", _m.PresencePenalty))
	builder.WriteString(", ")
	builder.WriteString("api_key_ciphertext=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// AIConfigs is a parsable slice of AIConfig.
type AIConfigs []*AIConfig
