// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/hoshikuzu/ent/aiconfig"
	"github.com/shuTwT/hoshikuzu/ent/predicate"
)

// AIConfigUpdate is the builder for updating AIConfig entities.
type AIConfigUpdate struct {
	config
	hooks    []Hook
	mutation *AIConfigMutation
}

// Where appends a list predicates to the AIConfigUpdate builder.
func (_u *AIConfigUpdate) Where(ps ...predicate.AIConfig) *AIConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AIConfigUpdate) SetUpdatedAt(v time.Time) *AIConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *AIConfigUpdate) SetBaseURL(v string) *AIConfigUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *AIConfigUpdate) SetNillableBaseURL(v *string) *AIConfigUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AIConfigUpdate) SetModel(v string) *AIConfigUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AIConfigUpdate) SetNillableModel(v *string) *AIConfigUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetTemperature sets the "temperature" field.
func (_u *AIConfigUpdate) SetTemperature(v float64) *AIConfigUpdate {
	_u.mutation.ResetTemperature()
	_u.mutation.SetTemperature(v)
	return _u
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_u *AIConfigUpdate) SetNillableTemperature(v *float64) *AIConfigUpdate {
	if v != nil {
		_u.SetTemperature(*v)
	}
	return _u
}

// AddTemperature adds value to the "temperature" field.
func (_u *AIConfigUpdate) AddTemperature(v float64) *AIConfigUpdate {
	_u.mutation.AddTemperature(v)
	return _u
}

// SetMaxTokens sets the "max_tokens" field.
func (_u *AIConfigUpdate) SetMaxTokens(v int) *AIConfigUpdate {
	_u.mutation.ResetMaxTokens()
	_u.mutation.SetMaxTokens(v)
	return _u
}

// SetNillableMaxTokens sets the "max_tokens" field if the given value is not nil.
func (_u *AIConfigUpdate) SetNillableMaxTokens(v *int) *AIConfigUpdate {
	if v != nil {
		_u.SetMaxTokens(*v)
	}
	return _u
}

// AddMaxTokens adds value to the "max_tokens" field.
func (_u *AIConfigUpdate) AddMaxTokens(v int) *AIConfigUpdate {
	_u.mutation.AddMaxTokens(v)
	return _u
}

// SetTopP sets the "top_p" field.
func (_u *AIConfigUpdate) SetTopP(v float64) *AIConfigUpdate {
	_u.mutation.ResetTopP()
	_u.mutation.SetTopP(v)
	return _u
}

// SetNillableTopP sets the "top_p" field if the given value is not nil.
func (_u *AIConfigUpdate) SetNillableTopP(v *float64) *AIConfigUpdate {
	if v != nil {
		_u.SetTopP(*v)
	}
	return _u
}

// AddTopP adds value to the "top_p" field.
func (_u *AIConfigUpdate) AddTopP(v float64) *AIConfigUpdate {
	_u.mutation.AddTopP(v)
	return _u
}

// SetFrequencyPenalty sets the "frequency_penalty" field.
func (_u *AIConfigUpdate) SetFrequencyPenalty(v float64) *AIConfigUpdate {
	_u.mutation.ResetFrequencyPenalty()
	_u.mutation.SetFrequencyPenalty(v)
	return _u
}

// SetNillableFrequencyPenalty sets the "frequency_penalty" field if the given value is not nil.
func (_u *AIConfigUpdate) SetNillableFrequencyPenalty(v *float64) *AIConfigUpdate {
	if v != nil {
		_u.SetFrequencyPenalty(*v)
	}
	return _u
}

// AddFrequencyPenalty adds value to the "frequency_penalty" field.
func (_u *AIConfigUpdate) AddFrequencyPenalty(v float64) *AIConfigUpdate {
	_u.mutation.AddFrequencyPenalty(v)
	return _u
}

// SetPresencePenalty sets the "presence_penalty" field.
func (_u *AIConfigUpdate) SetPresencePenalty(v float64) *AIConfigUpdate {
	_u.mutation.ResetPresencePenalty()
	_u.mutation.SetPresencePenalty(v)
	return _u
}

// SetNillablePresencePenalty sets the "presence_penalty" field if the given value is not nil.
func (_u *AIConfigUpdate) SetNillablePresencePenalty(v *float64) *AIConfigUpdate {
	if v != nil {
		_u.SetPresencePenalty(*v)
	}
	return _u
}

// AddPresencePenalty adds value to the "presence_penalty" field.
func (_u *AIConfigUpdate) AddPresencePenalty(v float64) *AIConfigUpdate {
	_u.mutation.AddPresencePenalty(v)
	return _u
}

// SetAPIKeyCiphertext sets the "api_key_ciphertext" field.
func (_u *AIConfigUpdate) SetAPIKeyCiphertext(v string) *AIConfigUpdate {
	_u.mutation.SetAPIKeyCiphertext(v)
	return _u
}

// SetNillableAPIKeyCiphertext sets the "api_key_ciphertext" field if the given value is not nil.
func (_u *AIConfigUpdate) SetNillableAPIKeyCiphertext(v *string) *AIConfigUpdate {
	if v != nil {
		_u.SetAPIKeyCiphertext(*v)
	}
	return _u
}

// Mutation returns the AIConfigMutation object of the builder.
func (_u *AIConfigUpdate) Mutation() *AIConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AIConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AIConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AIConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aiconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIConfigUpdate) check() error {
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := aiconfig.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "AIConfig.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := aiconfig.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AIConfig.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxTokens(); ok {
		if err := aiconfig.MaxTokensValidator(v); err != nil {
			return &ValidationError{Name: "max_tokens", err: fmt.Errorf(`ent: validator failed for field "AIConfig.max_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyCiphertext(); ok {
		if err := aiconfig.APIKeyCiphertextValidator(v); err != nil {
			return &ValidationError{Name: "api_key_ciphertext", err: fmt.Errorf(`ent: validator failed for field "AIConfig.api_key_ciphertext": %w`, err)}
		}
	}
	return nil
}

func (_u *AIConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aiconfig.Table, aiconfig.Columns, sqlgraph.NewFieldSpec(aiconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aiconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(aiconfig.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(aiconfig.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Temperature(); ok {
		_spec.SetField(aiconfig.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemperature(); ok {
		_spec.AddField(aiconfig.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxTokens(); ok {
		_spec.SetField(aiconfig.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTokens(); ok {
		_spec.AddField(aiconfig.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TopP(); ok {
		_spec.SetField(aiconfig.FieldTopP, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTopP(); ok {
		_spec.AddField(aiconfig.FieldTopP, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FrequencyPenalty(); ok {
		_spec.SetField(aiconfig.FieldFrequencyPenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrequencyPenalty(); ok {
		_spec.AddField(aiconfig.FieldFrequencyPenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PresencePenalty(); ok {
		_spec.SetField(aiconfig.FieldPresencePenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPresencePenalty(); ok {
		_spec.AddField(aiconfig.FieldPresencePenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.APIKeyCiphertext(); ok {
		_spec.SetField(aiconfig.FieldAPIKeyCiphertext, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AIConfigUpdateOne is the builder for updating a single AIConfig entity.
type AIConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AIConfigMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AIConfigUpdateOne) SetUpdatedAt(v time.Time) *AIConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *AIConfigUpdateOne) SetBaseURL(v string) *AIConfigUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *AIConfigUpdateOne) SetNillableBaseURL(v *string) *AIConfigUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AIConfigUpdateOne) SetModel(v string) *AIConfigUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AIConfigUpdateOne) SetNillableModel(v *string) *AIConfigUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetTemperature sets the "temperature" field.
func (_u *AIConfigUpdateOne) SetTemperature(v float64) *AIConfigUpdateOne {
	_u.mutation.ResetTemperature()
	_u.mutation.SetTemperature(v)
	return _u
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_u *AIConfigUpdateOne) SetNillableTemperature(v *float64) *AIConfigUpdateOne {
	if v != nil {
		_u.SetTemperature(*v)
	}
	return _u
}

// AddTemperature adds value to the "temperature" field.
func (_u *AIConfigUpdateOne) AddTemperature(v float64) *AIConfigUpdateOne {
	_u.mutation.AddTemperature(v)
	return _u
}

// SetMaxTokens sets the "max_tokens" field.
func (_u *AIConfigUpdateOne) SetMaxTokens(v int) *AIConfigUpdateOne {
	_u.mutation.ResetMaxTokens()
	_u.mutation.SetMaxTokens(v)
	return _u
}

// SetNillableMaxTokens sets the "max_tokens" field if the given value is not nil.
func (_u *AIConfigUpdateOne) SetNillableMaxTokens(v *int) *AIConfigUpdateOne {
	if v != nil {
		_u.SetMaxTokens(*v)
	}
	return _u
}

// AddMaxTokens adds value to the "max_tokens" field.
func (_u *AIConfigUpdateOne) AddMaxTokens(v int) *AIConfigUpdateOne {
	_u.mutation.AddMaxTokens(v)
	return _u
}

// SetTopP sets the "top_p" field.
func (_u *AIConfigUpdateOne) SetTopP(v float64) *AIConfigUpdateOne {
	_u.mutation.ResetTopP()
	_u.mutation.SetTopP(v)
	return _u
}

// SetNillableTopP sets the "top_p" field if the given value is not nil.
func (_u *AIConfigUpdateOne) SetNillableTopP(v *float64) *AIConfigUpdateOne {
	if v != nil {
		_u.SetTopP(*v)
	}
	return _u
}

// AddTopP adds value to the "top_p" field.
func (_u *AIConfigUpdateOne) AddTopP(v float64) *AIConfigUpdateOne {
	_u.mutation.AddTopP(v)
	return _u
}

// SetFrequencyPenalty sets the "frequency_penalty" field.
func (_u *AIConfigUpdateOne) SetFrequencyPenalty(v float64) *AIConfigUpdateOne {
	_u.mutation.ResetFrequencyPenalty()
	_u.mutation.SetFrequencyPenalty(v)
	return _u
}

// SetNillableFrequencyPenalty sets the "frequency_penalty" field if the given value is not nil.
func (_u *AIConfigUpdateOne) SetNillableFrequencyPenalty(v *float64) *AIConfigUpdateOne {
	if v != nil {
		_u.SetFrequencyPenalty(*v)
	}
	return _u
}

// AddFrequencyPenalty adds value to the "frequency_penalty" field.
func (_u *AIConfigUpdateOne) AddFrequencyPenalty(v float64) *AIConfigUpdateOne {
	_u.mutation.AddFrequencyPenalty(v)
	return _u
}

// SetPresencePenalty sets the "presence_penalty" field.
func (_u *AIConfigUpdateOne) SetPresencePenalty(v float64) *AIConfigUpdateOne {
	_u.mutation.ResetPresencePenalty()
	_u.mutation.SetPresencePenalty(v)
	return _u
}

// SetNillablePresencePenalty sets the "presence_penalty" field if the given value is not nil.
func (_u *AIConfigUpdateOne) SetNillablePresencePenalty(v *float64) *AIConfigUpdateOne {
	if v != nil {
		_u.SetPresencePenalty(*v)
	}
	return _u
}

// AddPresencePenalty adds value to the "presence_penalty" field.
func (_u *AIConfigUpdateOne) AddPresencePenalty(v float64) *AIConfigUpdateOne {
	_u.mutation.AddPresencePenalty(v)
	return _u
}

// SetAPIKeyCiphertext sets the "api_key_ciphertext" field.
func (_u *AIConfigUpdateOne) SetAPIKeyCiphertext(v string) *AIConfigUpdateOne {
	_u.mutation.SetAPIKeyCiphertext(v)
	return _u
}

// SetNillableAPIKeyCiphertext sets the "api_key_ciphertext" field if the given value is not nil.
func (_u *AIConfigUpdateOne) SetNillableAPIKeyCiphertext(v *string) *AIConfigUpdateOne {
	if v != nil {
		_u.SetAPIKeyCiphertext(*v)
	}
	return _u
}

// Mutation returns the AIConfigMutation object of the builder.
func (_u *AIConfigUpdateOne) Mutation() *AIConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the AIConfigUpdate builder.
func (_u *AIConfigUpdateOne) Where(ps ...predicate.AIConfig) *AIConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AIConfigUpdateOne) Select(field string, fields ...string) *AIConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AIConfig entity.
func (_u *AIConfigUpdateOne) Save(ctx context.Context) (*AIConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIConfigUpdateOne) SaveX(ctx context.Context) *AIConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AIConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AIConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aiconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIConfigUpdateOne) check() error {
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := aiconfig.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "AIConfig.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := aiconfig.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AIConfig.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxTokens(); ok {
		if err := aiconfig.MaxTokensValidator(v); err != nil {
			return &ValidationError{Name: "max_tokens", err: fmt.Errorf(`ent: validator failed for field "AIConfig.max_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyCiphertext(); ok {
		if err := aiconfig.APIKeyCiphertextValidator(v); err != nil {
			return &ValidationError{Name: "api_key_ciphertext", err: fmt.Errorf(`ent: validator failed for field "AIConfig.api_key_ciphertext": %w`, err)}
		}
	}
	return nil
}

func (_u *AIConfigUpdateOne) sqlSave(ctx context.Context) (_node *AIConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aiconfig.Table, aiconfig.Columns, sqlgraph.NewFieldSpec(aiconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AIConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aiconfig.FieldID)
		for _, f := range fields {
			if !aiconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aiconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aiconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(aiconfig.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(aiconfig.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Temperature(); ok {
		_spec.SetField(aiconfig.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemperature(); ok {
		_spec.AddField(aiconfig.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxTokens(); ok {
		_spec.SetField(aiconfig.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTokens(); ok {
		_spec.AddField(aiconfig.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TopP(); ok {
		_spec.SetField(aiconfig.FieldTopP, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTopP(); ok {
		_spec.AddField(aiconfig.FieldTopP, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FrequencyPenalty(); ok {
		_spec.SetField(aiconfig.FieldFrequencyPenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrequencyPenalty(); ok {
		_spec.AddField(aiconfig.FieldFrequencyPenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PresencePenalty(); ok {
		_spec.SetField(aiconfig.FieldPresencePenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPresencePenalty(); ok {
		_spec.AddField(aiconfig.FieldPresencePenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.APIKeyCiphertext(); ok {
		_spec.SetField(aiconfig.FieldAPIKeyCiphertext, field.TypeString, value)
	}
	_node = &AIConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
