// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/hoshikuzu/ent/aimodel"
	"github.com/shuTwT/hoshikuzu/ent/aiprovider"
	"github.com/shuTwT/hoshikuzu/ent/predicate"
)

// AIModelUpdate is the builder for updating AIModel entities.
type AIModelUpdate struct {
	config
	hooks    []Hook
	mutation *AIModelMutation
}

// Where appends a list predicates to the AIModelUpdate builder.
func (_u *AIModelUpdate) Where(ps ...predicate.AIModel) *AIModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AIModelUpdate) SetUpdatedAt(v time.Time) *AIModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *AIModelUpdate) SetProviderID(v int) *AIModelUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *AIModelUpdate) SetNillableProviderID(v *int) *AIModelUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *AIModelUpdate) SetModelName(v string) *AIModelUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *AIModelUpdate) SetNillableModelName(v *string) *AIModelUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *AIModelUpdate) SetDisplayName(v string) *AIModelUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *AIModelUpdate) SetNillableDisplayName(v *string) *AIModelUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *AIModelUpdate) ClearDisplayName() *AIModelUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *AIModelUpdate) SetIsEnabled(v bool) *AIModelUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *AIModelUpdate) SetNillableIsEnabled(v *bool) *AIModelUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *AIModelUpdate) SetSort(v int) *AIModelUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *AIModelUpdate) SetNillableSort(v *int) *AIModelUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *AIModelUpdate) AddSort(v int) *AIModelUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetProvider sets the "provider" edge to the AIProvider entity.
func (_u *AIModelUpdate) SetProvider(v *AIProvider) *AIModelUpdate {
	return _u.SetProviderID(v.ID)
}

// Mutation returns the AIModelMutation object of the builder.
func (_u *AIModelUpdate) Mutation() *AIModelMutation {
	return _u.mutation
}

// ClearProvider clears the "provider" edge to the AIProvider entity.
func (_u *AIModelUpdate) ClearProvider() *AIModelUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AIModelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AIModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AIModelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aimodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIModelUpdate) check() error {
	if v, ok := _u.mutation.ProviderID(); ok {
		if err := aimodel.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "AIModel.provider_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelName(); ok {
		if err := aimodel.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "AIModel.model_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := aimodel.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "AIModel.display_name": %w`, err)}
		}
	}
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AIModel.provider"`)
	}
	return nil
}

func (_u *AIModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aimodel.Table, aimodel.Columns, sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aimodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(aimodel.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(aimodel.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(aimodel.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(aimodel.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(aimodel.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(aimodel.FieldSort, field.TypeInt, value)
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aimodel.ProviderTable,
			Columns: []string{aimodel.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiprovider.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aimodel.ProviderTable,
			Columns: []string{aimodel.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiprovider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aimodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AIModelUpdateOne is the builder for updating a single AIModel entity.
type AIModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AIModelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AIModelUpdateOne) SetUpdatedAt(v time.Time) *AIModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *AIModelUpdateOne) SetProviderID(v int) *AIModelUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *AIModelUpdateOne) SetNillableProviderID(v *int) *AIModelUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *AIModelUpdateOne) SetModelName(v string) *AIModelUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *AIModelUpdateOne) SetNillableModelName(v *string) *AIModelUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *AIModelUpdateOne) SetDisplayName(v string) *AIModelUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *AIModelUpdateOne) SetNillableDisplayName(v *string) *AIModelUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *AIModelUpdateOne) ClearDisplayName() *AIModelUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *AIModelUpdateOne) SetIsEnabled(v bool) *AIModelUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *AIModelUpdateOne) SetNillableIsEnabled(v *bool) *AIModelUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *AIModelUpdateOne) SetSort(v int) *AIModelUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *AIModelUpdateOne) SetNillableSort(v *int) *AIModelUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *AIModelUpdateOne) AddSort(v int) *AIModelUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetProvider sets the "provider" edge to the AIProvider entity.
func (_u *AIModelUpdateOne) SetProvider(v *AIProvider) *AIModelUpdateOne {
	return _u.SetProviderID(v.ID)
}

// Mutation returns the AIModelMutation object of the builder.
func (_u *AIModelUpdateOne) Mutation() *AIModelMutation {
	return _u.mutation
}

// ClearProvider clears the "provider" edge to the AIProvider entity.
func (_u *AIModelUpdateOne) ClearProvider() *AIModelUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// Where appends a list predicates to the AIModelUpdate builder.
func (_u *AIModelUpdateOne) Where(ps ...predicate.AIModel) *AIModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AIModelUpdateOne) Select(field string, fields ...string) *AIModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AIModel entity.
func (_u *AIModelUpdateOne) Save(ctx context.Context) (*AIModel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIModelUpdateOne) SaveX(ctx context.Context) *AIModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AIModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AIModelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aimodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIModelUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderID(); ok {
		if err := aimodel.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "AIModel.provider_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelName(); ok {
		if err := aimodel.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "AIModel.model_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := aimodel.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "AIModel.display_name": %w`, err)}
		}
	}
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AIModel.provider"`)
	}
	return nil
}

func (_u *AIModelUpdateOne) sqlSave(ctx context.Context) (_node *AIModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aimodel.Table, aimodel.Columns, sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AIModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aimodel.FieldID)
		for _, f := range fields {
			if !aimodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aimodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aimodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(aimodel.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(aimodel.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(aimodel.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(aimodel.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(aimodel.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(aimodel.FieldSort, field.TypeInt, value)
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aimodel.ProviderTable,
			Columns: []string{aimodel.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiprovider.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aimodel.ProviderTable,
			Columns: []string{aimodel.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aiprovider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AIModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aimodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
