// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/hoshikuzu/ent/aimodel"
	"github.com/shuTwT/hoshikuzu/ent/aiprovider"
)

// AIModel is the model entity for the AIModel schema.
type AIModel struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 所属提供商 ID
	ProviderID int `json:"provider_id,omitempty"`
	// 模型名称（如 gpt-4o、deepseek-chat）
	ModelName string `json:"model_name,omitempty"`
	// 显示名称
	DisplayName string `json:"display_name,omitempty"`
	// 是否启用
	IsEnabled bool `json:"is_enabled,omitempty"`
	// 排序值，越小越靠前
	Sort int `json:"sort,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AIModelQuery when eager-loading is set.
	Edges        AIModelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AIModelEdges holds the relations/edges for other nodes in the graph.
type AIModelEdges struct {
	// 所属提供商
	Provider *AIProvider `json:"provider,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AIModelEdges) ProviderOrErr() (*AIProvider, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aiprovider.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AIModel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aimodel.FieldIsEnabled:
			values[i] = new(sql.NullBool)
		case aimodel.FieldID, aimodel.FieldProviderID, aimodel.FieldSort:
			values[i] = new(sql.NullInt64)
		case aimodel.FieldModelName, aimodel.FieldDisplayName:
			values[i] = new(sql.NullString)
		case aimodel.FieldCreatedAt, aimodel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AIModel fields.
func (_m *AIModel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aimodel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case aimodel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case aimodel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case aimodel.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = int(value.Int64)
			}
		case aimodel.FieldModelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_name", values[i])
			} else if value.Valid {
				_m.ModelName = value.String
			}
		case aimodel.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case aimodel.FieldIsEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enabled", values[i])
			} else if value.Valid {
				_m.IsEnabled = value.Bool
			}
		case aimodel.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AIModel.
// This includes values selected through modifiers, order, etc.
func (_m *AIModel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProvider queries the "provider" edge of the AIModel entity.
func (_m *AIModel) QueryProvider() *AIProviderQuery {
	return NewAIModelClient(_m.config).QueryProvider(_m)
}

// Update returns a builder for updating this AIModel.
// Note that you need to call AIModel.Unwrap() before calling this method if this AIModel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AIModel) Update() *AIModelUpdateOne {
	return NewAIModelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AIModel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AIModel) Unwrap() *AIModel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AIModel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AIModel) String() string {
	var builder strings.Builder
	builder.WriteString("AIModel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("model_name=")
	builder.WriteString(_m.ModelName)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("is_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsEnabled))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteByte(')')
	return builder.String()
}

// AIModels is a parsable slice of AIModel.
type AIModels []*AIModel
