// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/hoshikuzu/ent/aiprovider"
)

// AIProvider is the model entity for the AIProvider schema.
type AIProvider struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 提供商名称
	Name string `json:"name,omitempty"`
	// 提供商类型（openai/deepseek/moonshot/zhipu/volcengine/siliconflow/ollama/custom 等）
	ProviderType string `json:"provider_type,omitempty"`
	// OpenAI 兼容接口基础地址
	BaseURL string `json:"base_url,omitempty"`
	// AES-GCM 加密后的供应商 API Key，本地服务可留空
	APIKeyCiphertext string `json:"-"`
	// 温度
	Temperature float64 `json:"temperature,omitempty"`
	// 最大输出 Token
	MaxTokens int `json:"max_tokens,omitempty"`
	// Top P
	TopP float64 `json:"top_p,omitempty"`
	// 频率惩罚
	FrequencyPenalty float64 `json:"frequency_penalty,omitempty"`
	// 存在惩罚
	PresencePenalty float64 `json:"presence_penalty,omitempty"`
	// 是否默认提供商（AI 聊天与文章摘要使用）
	IsDefault bool `json:"is_default,omitempty"`
	// 是否启用
	IsEnabled bool `json:"is_enabled,omitempty"`
	// 排序值，越小越靠前
	Sort int `json:"sort,omitempty"`
	// 备注
	Remark string `json:"remark,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AIProviderQuery when eager-loading is set.
	Edges        AIProviderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AIProviderEdges holds the relations/edges for other nodes in the graph.
type AIProviderEdges struct {
	// 该提供商下的模型列表
	Models []*AIModel `json:"models,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ModelsOrErr returns the Models value or an error if the edge
// was not loaded in eager-loading.
func (e AIProviderEdges) ModelsOrErr() ([]*AIModel, error) {
	if e.loadedTypes[0] {
		return e.Models, nil
	}
	return nil, &NotLoadedError{edge: "models"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AIProvider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aiprovider.FieldIsDefault, aiprovider.FieldIsEnabled:
			values[i] = new(sql.NullBool)
		case aiprovider.FieldTemperature, aiprovider.FieldTopP, aiprovider.FieldFrequencyPenalty, aiprovider.FieldPresencePenalty:
			values[i] = new(sql.NullFloat64)
		case aiprovider.FieldID, aiprovider.FieldMaxTokens, aiprovider.FieldSort:
			values[i] = new(sql.NullInt64)
		case aiprovider.FieldName, aiprovider.FieldProviderType, aiprovider.FieldBaseURL, aiprovider.FieldAPIKeyCiphertext, aiprovider.FieldRemark:
			values[i] = new(sql.NullString)
		case aiprovider.FieldCreatedAt, aiprovider.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AIProvider fields.
func (_m *AIProvider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aiprovider.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case aiprovider.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case aiprovider.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case aiprovider.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case aiprovider.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				_m.ProviderType = value.String
			}
		case aiprovider.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case aiprovider.FieldAPIKeyCiphertext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_ciphertext", values[i])
			} else if value.Valid {
				_m.APIKeyCiphertext = value.String
			}
		case aiprovider.FieldTemperature:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field temperature", values[i])
			} else if value.Valid {
				_m.Temperature = value.Float64
			}
		case aiprovider.FieldMaxTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_tokens", values[i])
			} else if value.Valid {
				_m.MaxTokens = int(value.Int64)
			}
		case aiprovider.FieldTopP:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field top_p", values[i])
			} else if value.Valid {
				_m.TopP = value.Float64
			}
		case aiprovider.FieldFrequencyPenalty:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field frequency_penalty", values[i])
			} else if value.Valid {
				_m.FrequencyPenalty = value.Float64
			}
		case aiprovider.FieldPresencePenalty:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field presence_penalty", values[i])
			} else if value.Valid {
				_m.PresencePenalty = value.Float64
			}
		case aiprovider.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		case aiprovider.FieldIsEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enabled", values[i])
			} else if value.Valid {
				_m.IsEnabled = value.Bool
			}
		case aiprovider.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = int(value.Int64)
			}
		case aiprovider.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AIProvider.
// This includes values selected through modifiers, order, etc.
func (_m *AIProvider) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryModels queries the "models" edge of the AIProvider entity.
func (_m *AIProvider) QueryModels() *AIModelQuery {
	return NewAIProviderClient(_m.config).QueryModels(_m)
}

// Update returns a builder for updating this AIProvider.
// Note that you need to call AIProvider.Unwrap() before calling this method if this AIProvider
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AIProvider) Update() *AIProviderUpdateOne {
	return NewAIProviderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AIProvider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AIProvider) Unwrap() *AIProvider {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AIProvider is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AIProvider) String() string {
	var builder strings.Builder
	builder.WriteString("AIProvider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(_m.ProviderType)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("api_key_ciphertext=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("temperature=")
	builder.WriteString(fmt.Sprintf("%v", _m.Temperature))
	builder.WriteString(", ")
	builder.WriteString("max_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxTokens))
	builder.WriteString(", ")
	builder.WriteString("top_p=")
	builder.WriteString(fmt.Sprintf("%v", _m.TopP))
	builder.WriteString(", ")
	builder.WriteString("frequency_penalty=")
	builder.WriteString(fmt.Sprintf("%v", _m.FrequencyPenalty))
	builder.WriteString(", ")
	builder.WriteString("presence_penalty=")
	builder.WriteString(fmt.Sprintf("%v", _m.PresencePenalty))
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteString(", ")
	builder.WriteString("is_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsEnabled))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteByte(')')
	return builder.String()
}

// AIProviders is a parsable slice of AIProvider.
type AIProviders []*AIProvider
