// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/hoshikuzu/ent/aimodel"
	"github.com/shuTwT/hoshikuzu/ent/aiprovider"
	"github.com/shuTwT/hoshikuzu/ent/predicate"
)

// AIProviderUpdate is the builder for updating AIProvider entities.
type AIProviderUpdate struct {
	config
	hooks    []Hook
	mutation *AIProviderMutation
}

// Where appends a list predicates to the AIProviderUpdate builder.
func (_u *AIProviderUpdate) Where(ps ...predicate.AIProvider) *AIProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AIProviderUpdate) SetUpdatedAt(v time.Time) *AIProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AIProviderUpdate) SetName(v string) *AIProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillableName(v *string) *AIProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *AIProviderUpdate) SetProviderType(v string) *AIProviderUpdate {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillableProviderType(v *string) *AIProviderUpdate {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *AIProviderUpdate) SetBaseURL(v string) *AIProviderUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillableBaseURL(v *string) *AIProviderUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetAPIKeyCiphertext sets the "api_key_ciphertext" field.
func (_u *AIProviderUpdate) SetAPIKeyCiphertext(v string) *AIProviderUpdate {
	_u.mutation.SetAPIKeyCiphertext(v)
	return _u
}

// SetNillableAPIKeyCiphertext sets the "api_key_ciphertext" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillableAPIKeyCiphertext(v *string) *AIProviderUpdate {
	if v != nil {
		_u.SetAPIKeyCiphertext(*v)
	}
	return _u
}

// ClearAPIKeyCiphertext clears the value of the "api_key_ciphertext" field.
func (_u *AIProviderUpdate) ClearAPIKeyCiphertext() *AIProviderUpdate {
	_u.mutation.ClearAPIKeyCiphertext()
	return _u
}

// SetTemperature sets the "temperature" field.
func (_u *AIProviderUpdate) SetTemperature(v float64) *AIProviderUpdate {
	_u.mutation.ResetTemperature()
	_u.mutation.SetTemperature(v)
	return _u
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillableTemperature(v *float64) *AIProviderUpdate {
	if v != nil {
		_u.SetTemperature(*v)
	}
	return _u
}

// AddTemperature adds value to the "temperature" field.
func (_u *AIProviderUpdate) AddTemperature(v float64) *AIProviderUpdate {
	_u.mutation.AddTemperature(v)
	return _u
}

// SetMaxTokens sets the "max_tokens" field.
func (_u *AIProviderUpdate) SetMaxTokens(v int) *AIProviderUpdate {
	_u.mutation.ResetMaxTokens()
	_u.mutation.SetMaxTokens(v)
	return _u
}

// SetNillableMaxTokens sets the "max_tokens" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillableMaxTokens(v *int) *AIProviderUpdate {
	if v != nil {
		_u.SetMaxTokens(*v)
	}
	return _u
}

// AddMaxTokens adds value to the "max_tokens" field.
func (_u *AIProviderUpdate) AddMaxTokens(v int) *AIProviderUpdate {
	_u.mutation.AddMaxTokens(v)
	return _u
}

// SetTopP sets the "top_p" field.
func (_u *AIProviderUpdate) SetTopP(v float64) *AIProviderUpdate {
	_u.mutation.ResetTopP()
	_u.mutation.SetTopP(v)
	return _u
}

// SetNillableTopP sets the "top_p" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillableTopP(v *float64) *AIProviderUpdate {
	if v != nil {
		_u.SetTopP(*v)
	}
	return _u
}

// AddTopP adds value to the "top_p" field.
func (_u *AIProviderUpdate) AddTopP(v float64) *AIProviderUpdate {
	_u.mutation.AddTopP(v)
	return _u
}

// SetFrequencyPenalty sets the "frequency_penalty" field.
func (_u *AIProviderUpdate) SetFrequencyPenalty(v float64) *AIProviderUpdate {
	_u.mutation.ResetFrequencyPenalty()
	_u.mutation.SetFrequencyPenalty(v)
	return _u
}

// SetNillableFrequencyPenalty sets the "frequency_penalty" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillableFrequencyPenalty(v *float64) *AIProviderUpdate {
	if v != nil {
		_u.SetFrequencyPenalty(*v)
	}
	return _u
}

// AddFrequencyPenalty adds value to the "frequency_penalty" field.
func (_u *AIProviderUpdate) AddFrequencyPenalty(v float64) *AIProviderUpdate {
	_u.mutation.AddFrequencyPenalty(v)
	return _u
}

// SetPresencePenalty sets the "presence_penalty" field.
func (_u *AIProviderUpdate) SetPresencePenalty(v float64) *AIProviderUpdate {
	_u.mutation.ResetPresencePenalty()
	_u.mutation.SetPresencePenalty(v)
	return _u
}

// SetNillablePresencePenalty sets the "presence_penalty" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillablePresencePenalty(v *float64) *AIProviderUpdate {
	if v != nil {
		_u.SetPresencePenalty(*v)
	}
	return _u
}

// AddPresencePenalty adds value to the "presence_penalty" field.
func (_u *AIProviderUpdate) AddPresencePenalty(v float64) *AIProviderUpdate {
	_u.mutation.AddPresencePenalty(v)
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *AIProviderUpdate) SetIsDefault(v bool) *AIProviderUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillableIsDefault(v *bool) *AIProviderUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *AIProviderUpdate) SetIsEnabled(v bool) *AIProviderUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillableIsEnabled(v *bool) *AIProviderUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *AIProviderUpdate) SetSort(v int) *AIProviderUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillableSort(v *int) *AIProviderUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *AIProviderUpdate) AddSort(v int) *AIProviderUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *AIProviderUpdate) SetRemark(v string) *AIProviderUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *AIProviderUpdate) SetNillableRemark(v *string) *AIProviderUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *AIProviderUpdate) ClearRemark() *AIProviderUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// AddModelIDs adds the "models" edge to the AIModel entity by IDs.
func (_u *AIProviderUpdate) AddModelIDs(ids ...int) *AIProviderUpdate {
	_u.mutation.AddModelIDs(ids...)
	return _u
}

// AddModels adds the "models" edges to the AIModel entity.
func (_u *AIProviderUpdate) AddModels(v ...*AIModel) *AIProviderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelIDs(ids...)
}

// Mutation returns the AIProviderMutation object of the builder.
func (_u *AIProviderUpdate) Mutation() *AIProviderMutation {
	return _u.mutation
}

// ClearModels clears all "models" edges to the AIModel entity.
func (_u *AIProviderUpdate) ClearModels() *AIProviderUpdate {
	_u.mutation.ClearModels()
	return _u
}

// RemoveModelIDs removes the "models" edge to AIModel entities by IDs.
func (_u *AIProviderUpdate) RemoveModelIDs(ids ...int) *AIProviderUpdate {
	_u.mutation.RemoveModelIDs(ids...)
	return _u
}

// RemoveModels removes "models" edges to AIModel entities.
func (_u *AIProviderUpdate) RemoveModels(v ...*AIModel) *AIProviderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AIProviderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AIProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AIProviderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aiprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIProviderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := aiprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AIProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := aiprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "AIProvider.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := aiprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "AIProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxTokens(); ok {
		if err := aiprovider.MaxTokensValidator(v); err != nil {
			return &ValidationError{Name: "max_tokens", err: fmt.Errorf(`ent: validator failed for field "AIProvider.max_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := aiprovider.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "AIProvider.remark": %w`, err)}
		}
	}
	return nil
}

func (_u *AIProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aiprovider.Table, aiprovider.Columns, sqlgraph.NewFieldSpec(aiprovider.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aiprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(aiprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(aiprovider.FieldProviderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(aiprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyCiphertext(); ok {
		_spec.SetField(aiprovider.FieldAPIKeyCiphertext, field.TypeString, value)
	}
	if _u.mutation.APIKeyCiphertextCleared() {
		_spec.ClearField(aiprovider.FieldAPIKeyCiphertext, field.TypeString)
	}
	if value, ok := _u.mutation.Temperature(); ok {
		_spec.SetField(aiprovider.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemperature(); ok {
		_spec.AddField(aiprovider.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxTokens(); ok {
		_spec.SetField(aiprovider.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTokens(); ok {
		_spec.AddField(aiprovider.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TopP(); ok {
		_spec.SetField(aiprovider.FieldTopP, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTopP(); ok {
		_spec.AddField(aiprovider.FieldTopP, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FrequencyPenalty(); ok {
		_spec.SetField(aiprovider.FieldFrequencyPenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrequencyPenalty(); ok {
		_spec.AddField(aiprovider.FieldFrequencyPenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PresencePenalty(); ok {
		_spec.SetField(aiprovider.FieldPresencePenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPresencePenalty(); ok {
		_spec.AddField(aiprovider.FieldPresencePenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(aiprovider.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(aiprovider.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(aiprovider.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(aiprovider.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(aiprovider.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(aiprovider.FieldRemark, field.TypeString)
	}
	if _u.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiprovider.ModelsTable,
			Columns: []string{aiprovider.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelsIDs(); len(nodes) > 0 && !_u.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiprovider.ModelsTable,
			Columns: []string{aiprovider.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiprovider.ModelsTable,
			Columns: []string{aiprovider.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AIProviderUpdateOne is the builder for updating a single AIProvider entity.
type AIProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AIProviderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AIProviderUpdateOne) SetUpdatedAt(v time.Time) *AIProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AIProviderUpdateOne) SetName(v string) *AIProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillableName(v *string) *AIProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *AIProviderUpdateOne) SetProviderType(v string) *AIProviderUpdateOne {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillableProviderType(v *string) *AIProviderUpdateOne {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *AIProviderUpdateOne) SetBaseURL(v string) *AIProviderUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillableBaseURL(v *string) *AIProviderUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetAPIKeyCiphertext sets the "api_key_ciphertext" field.
func (_u *AIProviderUpdateOne) SetAPIKeyCiphertext(v string) *AIProviderUpdateOne {
	_u.mutation.SetAPIKeyCiphertext(v)
	return _u
}

// SetNillableAPIKeyCiphertext sets the "api_key_ciphertext" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillableAPIKeyCiphertext(v *string) *AIProviderUpdateOne {
	if v != nil {
		_u.SetAPIKeyCiphertext(*v)
	}
	return _u
}

// ClearAPIKeyCiphertext clears the value of the "api_key_ciphertext" field.
func (_u *AIProviderUpdateOne) ClearAPIKeyCiphertext() *AIProviderUpdateOne {
	_u.mutation.ClearAPIKeyCiphertext()
	return _u
}

// SetTemperature sets the "temperature" field.
func (_u *AIProviderUpdateOne) SetTemperature(v float64) *AIProviderUpdateOne {
	_u.mutation.ResetTemperature()
	_u.mutation.SetTemperature(v)
	return _u
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillableTemperature(v *float64) *AIProviderUpdateOne {
	if v != nil {
		_u.SetTemperature(*v)
	}
	return _u
}

// AddTemperature adds value to the "temperature" field.
func (_u *AIProviderUpdateOne) AddTemperature(v float64) *AIProviderUpdateOne {
	_u.mutation.AddTemperature(v)
	return _u
}

// SetMaxTokens sets the "max_tokens" field.
func (_u *AIProviderUpdateOne) SetMaxTokens(v int) *AIProviderUpdateOne {
	_u.mutation.ResetMaxTokens()
	_u.mutation.SetMaxTokens(v)
	return _u
}

// SetNillableMaxTokens sets the "max_tokens" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillableMaxTokens(v *int) *AIProviderUpdateOne {
	if v != nil {
		_u.SetMaxTokens(*v)
	}
	return _u
}

// AddMaxTokens adds value to the "max_tokens" field.
func (_u *AIProviderUpdateOne) AddMaxTokens(v int) *AIProviderUpdateOne {
	_u.mutation.AddMaxTokens(v)
	return _u
}

// SetTopP sets the "top_p" field.
func (_u *AIProviderUpdateOne) SetTopP(v float64) *AIProviderUpdateOne {
	_u.mutation.ResetTopP()
	_u.mutation.SetTopP(v)
	return _u
}

// SetNillableTopP sets the "top_p" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillableTopP(v *float64) *AIProviderUpdateOne {
	if v != nil {
		_u.SetTopP(*v)
	}
	return _u
}

// AddTopP adds value to the "top_p" field.
func (_u *AIProviderUpdateOne) AddTopP(v float64) *AIProviderUpdateOne {
	_u.mutation.AddTopP(v)
	return _u
}

// SetFrequencyPenalty sets the "frequency_penalty" field.
func (_u *AIProviderUpdateOne) SetFrequencyPenalty(v float64) *AIProviderUpdateOne {
	_u.mutation.ResetFrequencyPenalty()
	_u.mutation.SetFrequencyPenalty(v)
	return _u
}

// SetNillableFrequencyPenalty sets the "frequency_penalty" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillableFrequencyPenalty(v *float64) *AIProviderUpdateOne {
	if v != nil {
		_u.SetFrequencyPenalty(*v)
	}
	return _u
}

// AddFrequencyPenalty adds value to the "frequency_penalty" field.
func (_u *AIProviderUpdateOne) AddFrequencyPenalty(v float64) *AIProviderUpdateOne {
	_u.mutation.AddFrequencyPenalty(v)
	return _u
}

// SetPresencePenalty sets the "presence_penalty" field.
func (_u *AIProviderUpdateOne) SetPresencePenalty(v float64) *AIProviderUpdateOne {
	_u.mutation.ResetPresencePenalty()
	_u.mutation.SetPresencePenalty(v)
	return _u
}

// SetNillablePresencePenalty sets the "presence_penalty" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillablePresencePenalty(v *float64) *AIProviderUpdateOne {
	if v != nil {
		_u.SetPresencePenalty(*v)
	}
	return _u
}

// AddPresencePenalty adds value to the "presence_penalty" field.
func (_u *AIProviderUpdateOne) AddPresencePenalty(v float64) *AIProviderUpdateOne {
	_u.mutation.AddPresencePenalty(v)
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *AIProviderUpdateOne) SetIsDefault(v bool) *AIProviderUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillableIsDefault(v *bool) *AIProviderUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *AIProviderUpdateOne) SetIsEnabled(v bool) *AIProviderUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillableIsEnabled(v *bool) *AIProviderUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *AIProviderUpdateOne) SetSort(v int) *AIProviderUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillableSort(v *int) *AIProviderUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *AIProviderUpdateOne) AddSort(v int) *AIProviderUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *AIProviderUpdateOne) SetRemark(v string) *AIProviderUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *AIProviderUpdateOne) SetNillableRemark(v *string) *AIProviderUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *AIProviderUpdateOne) ClearRemark() *AIProviderUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// AddModelIDs adds the "models" edge to the AIModel entity by IDs.
func (_u *AIProviderUpdateOne) AddModelIDs(ids ...int) *AIProviderUpdateOne {
	_u.mutation.AddModelIDs(ids...)
	return _u
}

// AddModels adds the "models" edges to the AIModel entity.
func (_u *AIProviderUpdateOne) AddModels(v ...*AIModel) *AIProviderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelIDs(ids...)
}

// Mutation returns the AIProviderMutation object of the builder.
func (_u *AIProviderUpdateOne) Mutation() *AIProviderMutation {
	return _u.mutation
}

// ClearModels clears all "models" edges to the AIModel entity.
func (_u *AIProviderUpdateOne) ClearModels() *AIProviderUpdateOne {
	_u.mutation.ClearModels()
	return _u
}

// RemoveModelIDs removes the "models" edge to AIModel entities by IDs.
func (_u *AIProviderUpdateOne) RemoveModelIDs(ids ...int) *AIProviderUpdateOne {
	_u.mutation.RemoveModelIDs(ids...)
	return _u
}

// RemoveModels removes "models" edges to AIModel entities.
func (_u *AIProviderUpdateOne) RemoveModels(v ...*AIModel) *AIProviderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelIDs(ids...)
}

// Where appends a list predicates to the AIProviderUpdate builder.
func (_u *AIProviderUpdateOne) Where(ps ...predicate.AIProvider) *AIProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AIProviderUpdateOne) Select(field string, fields ...string) *AIProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AIProvider entity.
func (_u *AIProviderUpdateOne) Save(ctx context.Context) (*AIProvider, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AIProviderUpdateOne) SaveX(ctx context.Context) *AIProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AIProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AIProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AIProviderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aiprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AIProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := aiprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AIProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := aiprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "AIProvider.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := aiprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "AIProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxTokens(); ok {
		if err := aiprovider.MaxTokensValidator(v); err != nil {
			return &ValidationError{Name: "max_tokens", err: fmt.Errorf(`ent: validator failed for field "AIProvider.max_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := aiprovider.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "AIProvider.remark": %w`, err)}
		}
	}
	return nil
}

func (_u *AIProviderUpdateOne) sqlSave(ctx context.Context) (_node *AIProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aiprovider.Table, aiprovider.Columns, sqlgraph.NewFieldSpec(aiprovider.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AIProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aiprovider.FieldID)
		for _, f := range fields {
			if !aiprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aiprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aiprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(aiprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(aiprovider.FieldProviderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(aiprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyCiphertext(); ok {
		_spec.SetField(aiprovider.FieldAPIKeyCiphertext, field.TypeString, value)
	}
	if _u.mutation.APIKeyCiphertextCleared() {
		_spec.ClearField(aiprovider.FieldAPIKeyCiphertext, field.TypeString)
	}
	if value, ok := _u.mutation.Temperature(); ok {
		_spec.SetField(aiprovider.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemperature(); ok {
		_spec.AddField(aiprovider.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxTokens(); ok {
		_spec.SetField(aiprovider.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTokens(); ok {
		_spec.AddField(aiprovider.FieldMaxTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TopP(); ok {
		_spec.SetField(aiprovider.FieldTopP, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTopP(); ok {
		_spec.AddField(aiprovider.FieldTopP, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FrequencyPenalty(); ok {
		_spec.SetField(aiprovider.FieldFrequencyPenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrequencyPenalty(); ok {
		_spec.AddField(aiprovider.FieldFrequencyPenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PresencePenalty(); ok {
		_spec.SetField(aiprovider.FieldPresencePenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPresencePenalty(); ok {
		_spec.AddField(aiprovider.FieldPresencePenalty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(aiprovider.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(aiprovider.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(aiprovider.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(aiprovider.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(aiprovider.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(aiprovider.FieldRemark, field.TypeString)
	}
	if _u.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiprovider.ModelsTable,
			Columns: []string{aiprovider.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelsIDs(); len(nodes) > 0 && !_u.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiprovider.ModelsTable,
			Columns: []string{aiprovider.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiprovider.ModelsTable,
			Columns: []string{aiprovider.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aimodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AIProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
