// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/hoshikuzu/ent/payorder"
	"github.com/shuTwT/hoshikuzu/ent/post"
	"github.com/shuTwT/hoshikuzu/ent/postpurchase"
	"github.com/shuTwT/hoshikuzu/ent/user"
)

// PostPurchase is the model entity for the PostPurchase schema.
type PostPurchase struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 购买用户
	UserID int `json:"user_id,omitempty"`
	// 购买文章
	PostID int `json:"post_id,omitempty"`
	// 关联支付订单
	OrderID int `json:"order_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostPurchaseQuery when eager-loading is set.
	Edges        PostPurchaseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PostPurchaseEdges holds the relations/edges for other nodes in the graph.
type PostPurchaseEdges struct {
	// 购买用户
	User *User `json:"user,omitempty"`
	// 购买文章
	Post *Post `json:"post,omitempty"`
	// 关联支付订单
	Order *PayOrder `json:"order,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostPurchaseEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostPurchaseEdges) PostOrErr() (*Post, error) {
	if e.Post != nil {
		return e.Post, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "post"}
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostPurchaseEdges) OrderOrErr() (*PayOrder, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: payorder.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PostPurchase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case postpurchase.FieldID, postpurchase.FieldUserID, postpurchase.FieldPostID, postpurchase.FieldOrderID:
			values[i] = new(sql.NullInt64)
		case postpurchase.FieldCreatedAt, postpurchase.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PostPurchase fields.
func (_m *PostPurchase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case postpurchase.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case postpurchase.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case postpurchase.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case postpurchase.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case postpurchase.FieldPostID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value.Valid {
				_m.PostID = int(value.Int64)
			}
		case postpurchase.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PostPurchase.
// This includes values selected through modifiers, order, etc.
func (_m *PostPurchase) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PostPurchase entity.
func (_m *PostPurchase) QueryUser() *UserQuery {
	return NewPostPurchaseClient(_m.config).QueryUser(_m)
}

// QueryPost queries the "post" edge of the PostPurchase entity.
func (_m *PostPurchase) QueryPost() *PostQuery {
	return NewPostPurchaseClient(_m.config).QueryPost(_m)
}

// QueryOrder queries the "order" edge of the PostPurchase entity.
func (_m *PostPurchase) QueryOrder() *PayOrderQuery {
	return NewPostPurchaseClient(_m.config).QueryOrder(_m)
}

// Update returns a builder for updating this PostPurchase.
// Note that you need to call PostPurchase.Unwrap() before calling this method if this PostPurchase
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PostPurchase) Update() *PostPurchaseUpdateOne {
	return NewPostPurchaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PostPurchase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PostPurchase) Unwrap() *PostPurchase {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PostPurchase is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PostPurchase) String() string {
	var builder strings.Builder
	builder.WriteString("PostPurchase(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PostID))
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteByte(')')
	return builder.String()
}

// PostPurchases is a parsable slice of PostPurchase.
type PostPurchases []*PostPurchase
