// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gobee/ent/album"
	"gobee/ent/albumphoto"
	"gobee/ent/apiperms"
	"gobee/ent/comment"
	"gobee/ent/file"
	"gobee/ent/oauth2accesstoken"
	"gobee/ent/oauth2code"
	"gobee/ent/oauth2refreshtoken"
	"gobee/ent/page"
	"gobee/ent/paychannel"
	"gobee/ent/payorder"
	"gobee/ent/post"
	"gobee/ent/role"
	"gobee/ent/schema"
	"gobee/ent/setting"
	"gobee/ent/storagestrategy"
	"gobee/ent/user"
	"gobee/ent/webhook"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	albumMixin := schema.Album{}.Mixin()
	albumMixinFields0 := albumMixin[0].Fields()
	_ = albumMixinFields0
	albumFields := schema.Album{}.Fields()
	_ = albumFields
	// albumDescCreatedAt is the schema descriptor for created_at field.
	albumDescCreatedAt := albumMixinFields0[1].Descriptor()
	// album.DefaultCreatedAt holds the default value on creation for the created_at field.
	album.DefaultCreatedAt = albumDescCreatedAt.Default.(func() time.Time)
	// albumDescUpdatedAt is the schema descriptor for updated_at field.
	albumDescUpdatedAt := albumMixinFields0[2].Descriptor()
	// album.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	album.DefaultUpdatedAt = albumDescUpdatedAt.Default.(func() time.Time)
	// album.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	album.UpdateDefaultUpdatedAt = albumDescUpdatedAt.UpdateDefault.(func() time.Time)
	// albumDescName is the schema descriptor for name field.
	albumDescName := albumFields[0].Descriptor()
	// album.NameValidator is a validator for the "name" field. It is called by the builders before save.
	album.NameValidator = albumDescName.Validators[0].(func(string) error)
	// albumDescDescription is the schema descriptor for description field.
	albumDescDescription := albumFields[1].Descriptor()
	// album.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	album.DescriptionValidator = albumDescDescription.Validators[0].(func(string) error)
	// albumDescSort is the schema descriptor for sort field.
	albumDescSort := albumFields[2].Descriptor()
	// album.DefaultSort holds the default value on creation for the sort field.
	album.DefaultSort = albumDescSort.Default.(int)
	albumphotoMixin := schema.AlbumPhoto{}.Mixin()
	albumphotoMixinFields0 := albumphotoMixin[0].Fields()
	_ = albumphotoMixinFields0
	albumphotoFields := schema.AlbumPhoto{}.Fields()
	_ = albumphotoFields
	// albumphotoDescCreatedAt is the schema descriptor for created_at field.
	albumphotoDescCreatedAt := albumphotoMixinFields0[1].Descriptor()
	// albumphoto.DefaultCreatedAt holds the default value on creation for the created_at field.
	albumphoto.DefaultCreatedAt = albumphotoDescCreatedAt.Default.(func() time.Time)
	// albumphotoDescUpdatedAt is the schema descriptor for updated_at field.
	albumphotoDescUpdatedAt := albumphotoMixinFields0[2].Descriptor()
	// albumphoto.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	albumphoto.DefaultUpdatedAt = albumphotoDescUpdatedAt.Default.(func() time.Time)
	// albumphoto.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	albumphoto.UpdateDefaultUpdatedAt = albumphotoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// albumphotoDescViewCount is the schema descriptor for view_count field.
	albumphotoDescViewCount := albumphotoFields[1].Descriptor()
	// albumphoto.DefaultViewCount holds the default value on creation for the view_count field.
	albumphoto.DefaultViewCount = albumphotoDescViewCount.Default.(int)
	apipermsMixin := schema.ApiPerms{}.Mixin()
	apipermsMixinFields0 := apipermsMixin[0].Fields()
	_ = apipermsMixinFields0
	apipermsFields := schema.ApiPerms{}.Fields()
	_ = apipermsFields
	// apipermsDescCreatedAt is the schema descriptor for created_at field.
	apipermsDescCreatedAt := apipermsMixinFields0[1].Descriptor()
	// apiperms.DefaultCreatedAt holds the default value on creation for the created_at field.
	apiperms.DefaultCreatedAt = apipermsDescCreatedAt.Default.(func() time.Time)
	// apipermsDescUpdatedAt is the schema descriptor for updated_at field.
	apipermsDescUpdatedAt := apipermsMixinFields0[2].Descriptor()
	// apiperms.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apiperms.DefaultUpdatedAt = apipermsDescUpdatedAt.Default.(func() time.Time)
	// apiperms.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apiperms.UpdateDefaultUpdatedAt = apipermsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apipermsDescPermissionType is the schema descriptor for permission_type field.
	apipermsDescPermissionType := apipermsFields[4].Descriptor()
	// apiperms.DefaultPermissionType holds the default value on creation for the permission_type field.
	apiperms.DefaultPermissionType = apipermsDescPermissionType.Default.(string)
	// apipermsDescRoles is the schema descriptor for roles field.
	apipermsDescRoles := apipermsFields[5].Descriptor()
	// apiperms.DefaultRoles holds the default value on creation for the roles field.
	apiperms.DefaultRoles = apipermsDescRoles.Default.([]string)
	// apipermsDescStatus is the schema descriptor for status field.
	apipermsDescStatus := apipermsFields[6].Descriptor()
	// apiperms.DefaultStatus holds the default value on creation for the status field.
	apiperms.DefaultStatus = apipermsDescStatus.Default.(string)
	commentMixin := schema.Comment{}.Mixin()
	commentMixinFields0 := commentMixin[0].Fields()
	_ = commentMixinFields0
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentMixinFields0[1].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentMixinFields0[2].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(func() time.Time)
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// commentDescContent is the schema descriptor for content field.
	commentDescContent := commentFields[2].Descriptor()
	// comment.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	comment.ContentValidator = func() func(string) error {
		validators := commentDescContent.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(content string) error {
			for _, fn := range fns {
				if err := fn(content); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// commentDescIPAddress is the schema descriptor for ip_address field.
	commentDescIPAddress := commentFields[6].Descriptor()
	// comment.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	comment.IPAddressValidator = commentDescIPAddress.Validators[0].(func(string) error)
	// commentDescIPLocation is the schema descriptor for ip_location field.
	commentDescIPLocation := commentFields[7].Descriptor()
	// comment.IPLocationValidator is a validator for the "ip_location" field. It is called by the builders before save.
	comment.IPLocationValidator = commentDescIPLocation.Validators[0].(func(string) error)
	// commentDescPinned is the schema descriptor for pinned field.
	commentDescPinned := commentFields[8].Descriptor()
	// comment.DefaultPinned holds the default value on creation for the pinned field.
	comment.DefaultPinned = commentDescPinned.Default.(bool)
	fileMixin := schema.File{}.Mixin()
	fileMixinFields0 := fileMixin[0].Fields()
	_ = fileMixinFields0
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescCreatedAt is the schema descriptor for created_at field.
	fileDescCreatedAt := fileMixinFields0[1].Descriptor()
	// file.DefaultCreatedAt holds the default value on creation for the created_at field.
	file.DefaultCreatedAt = fileDescCreatedAt.Default.(func() time.Time)
	// fileDescUpdatedAt is the schema descriptor for updated_at field.
	fileDescUpdatedAt := fileMixinFields0[2].Descriptor()
	// file.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	file.DefaultUpdatedAt = fileDescUpdatedAt.Default.(func() time.Time)
	// file.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	file.UpdateDefaultUpdatedAt = fileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// fileDescName is the schema descriptor for name field.
	fileDescName := fileFields[0].Descriptor()
	// file.NameValidator is a validator for the "name" field. It is called by the builders before save.
	file.NameValidator = func() func(string) error {
		validators := fileDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// fileDescPath is the schema descriptor for path field.
	fileDescPath := fileFields[1].Descriptor()
	// file.DefaultPath holds the default value on creation for the path field.
	file.DefaultPath = fileDescPath.Default.(string)
	// file.PathValidator is a validator for the "path" field. It is called by the builders before save.
	file.PathValidator = fileDescPath.Validators[0].(func(string) error)
	// fileDescURL is the schema descriptor for url field.
	fileDescURL := fileFields[2].Descriptor()
	// file.URLValidator is a validator for the "url" field. It is called by the builders before save.
	file.URLValidator = func() func(string) error {
		validators := fileDescURL.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(url string) error {
			for _, fn := range fns {
				if err := fn(url); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	oauth2accesstokenMixin := schema.Oauth2AccessToken{}.Mixin()
	oauth2accesstokenMixinFields0 := oauth2accesstokenMixin[0].Fields()
	_ = oauth2accesstokenMixinFields0
	oauth2accesstokenFields := schema.Oauth2AccessToken{}.Fields()
	_ = oauth2accesstokenFields
	// oauth2accesstokenDescCreatedAt is the schema descriptor for created_at field.
	oauth2accesstokenDescCreatedAt := oauth2accesstokenMixinFields0[1].Descriptor()
	// oauth2accesstoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauth2accesstoken.DefaultCreatedAt = oauth2accesstokenDescCreatedAt.Default.(func() time.Time)
	// oauth2accesstokenDescUpdatedAt is the schema descriptor for updated_at field.
	oauth2accesstokenDescUpdatedAt := oauth2accesstokenMixinFields0[2].Descriptor()
	// oauth2accesstoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauth2accesstoken.DefaultUpdatedAt = oauth2accesstokenDescUpdatedAt.Default.(func() time.Time)
	// oauth2accesstoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauth2accesstoken.UpdateDefaultUpdatedAt = oauth2accesstokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauth2accesstokenDescAccessToken is the schema descriptor for access_token field.
	oauth2accesstokenDescAccessToken := oauth2accesstokenFields[1].Descriptor()
	// oauth2accesstoken.AccessTokenValidator is a validator for the "access_token" field. It is called by the builders before save.
	oauth2accesstoken.AccessTokenValidator = func() func(string) error {
		validators := oauth2accesstokenDescAccessToken.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(access_token string) error {
			for _, fn := range fns {
				if err := fn(access_token); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauth2accesstokenDescRefreshToken is the schema descriptor for refresh_token field.
	oauth2accesstokenDescRefreshToken := oauth2accesstokenFields[2].Descriptor()
	// oauth2accesstoken.RefreshTokenValidator is a validator for the "refresh_token" field. It is called by the builders before save.
	oauth2accesstoken.RefreshTokenValidator = func() func(string) error {
		validators := oauth2accesstokenDescRefreshToken.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(refresh_token string) error {
			for _, fn := range fns {
				if err := fn(refresh_token); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauth2accesstokenDescClientID is the schema descriptor for client_id field.
	oauth2accesstokenDescClientID := oauth2accesstokenFields[3].Descriptor()
	// oauth2accesstoken.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauth2accesstoken.ClientIDValidator = func() func(string) error {
		validators := oauth2accesstokenDescClientID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(client_id string) error {
			for _, fn := range fns {
				if err := fn(client_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauth2accesstokenDescScope is the schema descriptor for scope field.
	oauth2accesstokenDescScope := oauth2accesstokenFields[4].Descriptor()
	// oauth2accesstoken.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	oauth2accesstoken.ScopeValidator = func() func(string) error {
		validators := oauth2accesstokenDescScope.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(scope string) error {
			for _, fn := range fns {
				if err := fn(scope); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	oauth2codeMixin := schema.Oauth2Code{}.Mixin()
	oauth2codeMixinFields0 := oauth2codeMixin[0].Fields()
	_ = oauth2codeMixinFields0
	oauth2codeFields := schema.Oauth2Code{}.Fields()
	_ = oauth2codeFields
	// oauth2codeDescCreatedAt is the schema descriptor for created_at field.
	oauth2codeDescCreatedAt := oauth2codeMixinFields0[1].Descriptor()
	// oauth2code.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauth2code.DefaultCreatedAt = oauth2codeDescCreatedAt.Default.(func() time.Time)
	// oauth2codeDescUpdatedAt is the schema descriptor for updated_at field.
	oauth2codeDescUpdatedAt := oauth2codeMixinFields0[2].Descriptor()
	// oauth2code.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauth2code.DefaultUpdatedAt = oauth2codeDescUpdatedAt.Default.(func() time.Time)
	// oauth2code.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauth2code.UpdateDefaultUpdatedAt = oauth2codeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauth2codeDescCode is the schema descriptor for code field.
	oauth2codeDescCode := oauth2codeFields[1].Descriptor()
	// oauth2code.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	oauth2code.CodeValidator = func() func(string) error {
		validators := oauth2codeDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauth2codeDescClientID is the schema descriptor for client_id field.
	oauth2codeDescClientID := oauth2codeFields[3].Descriptor()
	// oauth2code.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauth2code.ClientIDValidator = func() func(string) error {
		validators := oauth2codeDescClientID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(client_id string) error {
			for _, fn := range fns {
				if err := fn(client_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauth2codeDescRedirectURI is the schema descriptor for redirect_uri field.
	oauth2codeDescRedirectURI := oauth2codeFields[4].Descriptor()
	// oauth2code.RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	oauth2code.RedirectURIValidator = func() func(string) error {
		validators := oauth2codeDescRedirectURI.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(redirect_uri string) error {
			for _, fn := range fns {
				if err := fn(redirect_uri); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauth2codeDescScope is the schema descriptor for scope field.
	oauth2codeDescScope := oauth2codeFields[5].Descriptor()
	// oauth2code.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	oauth2code.ScopeValidator = func() func(string) error {
		validators := oauth2codeDescScope.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(scope string) error {
			for _, fn := range fns {
				if err := fn(scope); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	oauth2refreshtokenMixin := schema.Oauth2RefreshToken{}.Mixin()
	oauth2refreshtokenMixinFields0 := oauth2refreshtokenMixin[0].Fields()
	_ = oauth2refreshtokenMixinFields0
	oauth2refreshtokenFields := schema.Oauth2RefreshToken{}.Fields()
	_ = oauth2refreshtokenFields
	// oauth2refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	oauth2refreshtokenDescCreatedAt := oauth2refreshtokenMixinFields0[1].Descriptor()
	// oauth2refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauth2refreshtoken.DefaultCreatedAt = oauth2refreshtokenDescCreatedAt.Default.(func() time.Time)
	// oauth2refreshtokenDescUpdatedAt is the schema descriptor for updated_at field.
	oauth2refreshtokenDescUpdatedAt := oauth2refreshtokenMixinFields0[2].Descriptor()
	// oauth2refreshtoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauth2refreshtoken.DefaultUpdatedAt = oauth2refreshtokenDescUpdatedAt.Default.(func() time.Time)
	// oauth2refreshtoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauth2refreshtoken.UpdateDefaultUpdatedAt = oauth2refreshtokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauth2refreshtokenDescRefreshToken is the schema descriptor for refresh_token field.
	oauth2refreshtokenDescRefreshToken := oauth2refreshtokenFields[1].Descriptor()
	// oauth2refreshtoken.RefreshTokenValidator is a validator for the "refresh_token" field. It is called by the builders before save.
	oauth2refreshtoken.RefreshTokenValidator = func() func(string) error {
		validators := oauth2refreshtokenDescRefreshToken.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(refresh_token string) error {
			for _, fn := range fns {
				if err := fn(refresh_token); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauth2refreshtokenDescClientID is the schema descriptor for client_id field.
	oauth2refreshtokenDescClientID := oauth2refreshtokenFields[2].Descriptor()
	// oauth2refreshtoken.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauth2refreshtoken.ClientIDValidator = func() func(string) error {
		validators := oauth2refreshtokenDescClientID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(client_id string) error {
			for _, fn := range fns {
				if err := fn(client_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauth2refreshtokenDescScope is the schema descriptor for scope field.
	oauth2refreshtokenDescScope := oauth2refreshtokenFields[3].Descriptor()
	// oauth2refreshtoken.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	oauth2refreshtoken.ScopeValidator = func() func(string) error {
		validators := oauth2refreshtokenDescScope.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(scope string) error {
			for _, fn := range fns {
				if err := fn(scope); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	pageMixin := schema.Page{}.Mixin()
	pageMixinFields0 := pageMixin[0].Fields()
	_ = pageMixinFields0
	pageFields := schema.Page{}.Fields()
	_ = pageFields
	// pageDescCreatedAt is the schema descriptor for created_at field.
	pageDescCreatedAt := pageMixinFields0[1].Descriptor()
	// page.DefaultCreatedAt holds the default value on creation for the created_at field.
	page.DefaultCreatedAt = pageDescCreatedAt.Default.(func() time.Time)
	// pageDescUpdatedAt is the schema descriptor for updated_at field.
	pageDescUpdatedAt := pageMixinFields0[2].Descriptor()
	// page.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	page.DefaultUpdatedAt = pageDescUpdatedAt.Default.(func() time.Time)
	// page.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	page.UpdateDefaultUpdatedAt = pageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// pageDescTitle is the schema descriptor for title field.
	pageDescTitle := pageFields[0].Descriptor()
	// page.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	page.TitleValidator = func() func(string) error {
		validators := pageDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pageDescContent is the schema descriptor for content field.
	pageDescContent := pageFields[1].Descriptor()
	// page.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	page.ContentValidator = pageDescContent.Validators[0].(func(string) error)
	paychannelMixin := schema.PayChannel{}.Mixin()
	paychannelMixinFields0 := paychannelMixin[0].Fields()
	_ = paychannelMixinFields0
	paychannelFields := schema.PayChannel{}.Fields()
	_ = paychannelFields
	// paychannelDescCreatedAt is the schema descriptor for created_at field.
	paychannelDescCreatedAt := paychannelMixinFields0[1].Descriptor()
	// paychannel.DefaultCreatedAt holds the default value on creation for the created_at field.
	paychannel.DefaultCreatedAt = paychannelDescCreatedAt.Default.(func() time.Time)
	// paychannelDescUpdatedAt is the schema descriptor for updated_at field.
	paychannelDescUpdatedAt := paychannelMixinFields0[2].Descriptor()
	// paychannel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paychannel.DefaultUpdatedAt = paychannelDescUpdatedAt.Default.(func() time.Time)
	// paychannel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paychannel.UpdateDefaultUpdatedAt = paychannelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paychannelDescName is the schema descriptor for name field.
	paychannelDescName := paychannelFields[0].Descriptor()
	// paychannel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	paychannel.NameValidator = func() func(string) error {
		validators := paychannelDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// paychannelDescCode is the schema descriptor for code field.
	paychannelDescCode := paychannelFields[1].Descriptor()
	// paychannel.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	paychannel.CodeValidator = func() func(string) error {
		validators := paychannelDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// paychannelDescType is the schema descriptor for type field.
	paychannelDescType := paychannelFields[2].Descriptor()
	// paychannel.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	paychannel.TypeValidator = func() func(string) error {
		validators := paychannelDescType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_type string) error {
			for _, fn := range fns {
				if err := fn(_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	payorderMixin := schema.PayOrder{}.Mixin()
	payorderMixinFields0 := payorderMixin[0].Fields()
	_ = payorderMixinFields0
	payorderFields := schema.PayOrder{}.Fields()
	_ = payorderFields
	// payorderDescCreatedAt is the schema descriptor for created_at field.
	payorderDescCreatedAt := payorderMixinFields0[1].Descriptor()
	// payorder.DefaultCreatedAt holds the default value on creation for the created_at field.
	payorder.DefaultCreatedAt = payorderDescCreatedAt.Default.(func() time.Time)
	// payorderDescUpdatedAt is the schema descriptor for updated_at field.
	payorderDescUpdatedAt := payorderMixinFields0[2].Descriptor()
	// payorder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	payorder.DefaultUpdatedAt = payorderDescUpdatedAt.Default.(func() time.Time)
	// payorder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	payorder.UpdateDefaultUpdatedAt = payorderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// payorderDescState is the schema descriptor for state field.
	payorderDescState := payorderFields[10].Descriptor()
	// payorder.DefaultState holds the default value on creation for the state field.
	payorder.DefaultState = payorderDescState.Default.(string)
	postMixin := schema.Post{}.Mixin()
	postMixinFields0 := postMixin[0].Fields()
	_ = postMixinFields0
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postMixinFields0[1].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for updated_at field.
	postDescUpdatedAt := postMixinFields0[2].Descriptor()
	// post.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	post.DefaultUpdatedAt = postDescUpdatedAt.Default.(func() time.Time)
	// post.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
	// postDescTitle is the schema descriptor for title field.
	postDescTitle := postFields[0].Descriptor()
	// post.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	post.TitleValidator = func() func(string) error {
		validators := postDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// postDescAlias is the schema descriptor for alias field.
	postDescAlias := postFields[1].Descriptor()
	// post.AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	post.AliasValidator = func() func(string) error {
		validators := postDescAlias.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(alias string) error {
			for _, fn := range fns {
				if err := fn(alias); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// postDescContent is the schema descriptor for content field.
	postDescContent := postFields[2].Descriptor()
	// post.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	post.ContentValidator = postDescContent.Validators[0].(func(string) error)
	// postDescIsPublished is the schema descriptor for is_published field.
	postDescIsPublished := postFields[3].Descriptor()
	// post.DefaultIsPublished holds the default value on creation for the is_published field.
	post.DefaultIsPublished = postDescIsPublished.Default.(bool)
	// postDescIsAutogenSummary is the schema descriptor for is_autogen_summary field.
	postDescIsAutogenSummary := postFields[4].Descriptor()
	// post.DefaultIsAutogenSummary holds the default value on creation for the is_autogen_summary field.
	post.DefaultIsAutogenSummary = postDescIsAutogenSummary.Default.(bool)
	// postDescIsVisible is the schema descriptor for is_visible field.
	postDescIsVisible := postFields[5].Descriptor()
	// post.DefaultIsVisible holds the default value on creation for the is_visible field.
	post.DefaultIsVisible = postDescIsVisible.Default.(bool)
	// postDescIsTipToTop is the schema descriptor for is_tip_to_top field.
	postDescIsTipToTop := postFields[6].Descriptor()
	// post.DefaultIsTipToTop holds the default value on creation for the is_tip_to_top field.
	post.DefaultIsTipToTop = postDescIsTipToTop.Default.(bool)
	// postDescIsAllowComment is the schema descriptor for is_allow_comment field.
	postDescIsAllowComment := postFields[7].Descriptor()
	// post.DefaultIsAllowComment holds the default value on creation for the is_allow_comment field.
	post.DefaultIsAllowComment = postDescIsAllowComment.Default.(bool)
	// postDescViewCount is the schema descriptor for view_count field.
	postDescViewCount := postFields[9].Descriptor()
	// post.DefaultViewCount holds the default value on creation for the view_count field.
	post.DefaultViewCount = postDescViewCount.Default.(int)
	// post.ViewCountValidator is a validator for the "view_count" field. It is called by the builders before save.
	post.ViewCountValidator = postDescViewCount.Validators[0].(func(int) error)
	// postDescCommentCount is the schema descriptor for comment_count field.
	postDescCommentCount := postFields[10].Descriptor()
	// post.DefaultCommentCount holds the default value on creation for the comment_count field.
	post.DefaultCommentCount = postDescCommentCount.Default.(int)
	// post.CommentCountValidator is a validator for the "comment_count" field. It is called by the builders before save.
	post.CommentCountValidator = postDescCommentCount.Validators[0].(func(int) error)
	// postDescCover is the schema descriptor for cover field.
	postDescCover := postFields[11].Descriptor()
	// post.CoverValidator is a validator for the "cover" field. It is called by the builders before save.
	post.CoverValidator = postDescCover.Validators[0].(func(string) error)
	// postDescKeywords is the schema descriptor for keywords field.
	postDescKeywords := postFields[12].Descriptor()
	// post.KeywordsValidator is a validator for the "keywords" field. It is called by the builders before save.
	post.KeywordsValidator = postDescKeywords.Validators[0].(func(string) error)
	// postDescCopyright is the schema descriptor for copyright field.
	postDescCopyright := postFields[13].Descriptor()
	// post.CopyrightValidator is a validator for the "copyright" field. It is called by the builders before save.
	post.CopyrightValidator = postDescCopyright.Validators[0].(func(string) error)
	// postDescAuthor is the schema descriptor for author field.
	postDescAuthor := postFields[14].Descriptor()
	// post.DefaultAuthor holds the default value on creation for the author field.
	post.DefaultAuthor = postDescAuthor.Default.(string)
	// postDescSummary is the schema descriptor for summary field.
	postDescSummary := postFields[15].Descriptor()
	// post.SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	post.SummaryValidator = postDescSummary.Validators[0].(func(string) error)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[2].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[0].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = func() func(string) error {
		validators := roleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescCode is the schema descriptor for code field.
	roleDescCode := roleFields[1].Descriptor()
	// role.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	role.CodeValidator = func() func(string) error {
		validators := roleDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescDescription is the schema descriptor for description field.
	roleDescDescription := roleFields[2].Descriptor()
	// role.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	role.DescriptionValidator = roleDescDescription.Validators[0].(func(string) error)
	// roleDescIsDefault is the schema descriptor for is_default field.
	roleDescIsDefault := roleFields[3].Descriptor()
	// role.DefaultIsDefault holds the default value on creation for the is_default field.
	role.DefaultIsDefault = roleDescIsDefault.Default.(bool)
	settingMixin := schema.Setting{}.Mixin()
	settingMixinFields0 := settingMixin[0].Fields()
	_ = settingMixinFields0
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingMixinFields0[1].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingMixinFields0[2].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[0].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = func() func(string) error {
		validators := settingDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// settingDescValue is the schema descriptor for value field.
	settingDescValue := settingFields[1].Descriptor()
	// setting.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	setting.ValueValidator = func() func(string) error {
		validators := settingDescValue.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(value string) error {
			for _, fn := range fns {
				if err := fn(value); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// settingDescComment is the schema descriptor for comment field.
	settingDescComment := settingFields[2].Descriptor()
	// setting.CommentValidator is a validator for the "comment" field. It is called by the builders before save.
	setting.CommentValidator = settingDescComment.Validators[0].(func(string) error)
	storagestrategyMixin := schema.StorageStrategy{}.Mixin()
	storagestrategyMixinFields0 := storagestrategyMixin[0].Fields()
	_ = storagestrategyMixinFields0
	storagestrategyFields := schema.StorageStrategy{}.Fields()
	_ = storagestrategyFields
	// storagestrategyDescCreatedAt is the schema descriptor for created_at field.
	storagestrategyDescCreatedAt := storagestrategyMixinFields0[1].Descriptor()
	// storagestrategy.DefaultCreatedAt holds the default value on creation for the created_at field.
	storagestrategy.DefaultCreatedAt = storagestrategyDescCreatedAt.Default.(func() time.Time)
	// storagestrategyDescUpdatedAt is the schema descriptor for updated_at field.
	storagestrategyDescUpdatedAt := storagestrategyMixinFields0[2].Descriptor()
	// storagestrategy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	storagestrategy.DefaultUpdatedAt = storagestrategyDescUpdatedAt.Default.(func() time.Time)
	// storagestrategy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	storagestrategy.UpdateDefaultUpdatedAt = storagestrategyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// storagestrategyDescName is the schema descriptor for name field.
	storagestrategyDescName := storagestrategyFields[0].Descriptor()
	// storagestrategy.NameValidator is a validator for the "name" field. It is called by the builders before save.
	storagestrategy.NameValidator = storagestrategyDescName.Validators[0].(func(string) error)
	// storagestrategyDescNodeID is the schema descriptor for node_id field.
	storagestrategyDescNodeID := storagestrategyFields[2].Descriptor()
	// storagestrategy.DefaultNodeID holds the default value on creation for the node_id field.
	storagestrategy.DefaultNodeID = storagestrategyDescNodeID.Default.(string)
	// storagestrategyDescEndpoint is the schema descriptor for endpoint field.
	storagestrategyDescEndpoint := storagestrategyFields[3].Descriptor()
	// storagestrategy.DefaultEndpoint holds the default value on creation for the endpoint field.
	storagestrategy.DefaultEndpoint = storagestrategyDescEndpoint.Default.(string)
	// storagestrategyDescRegion is the schema descriptor for region field.
	storagestrategyDescRegion := storagestrategyFields[4].Descriptor()
	// storagestrategy.DefaultRegion holds the default value on creation for the region field.
	storagestrategy.DefaultRegion = storagestrategyDescRegion.Default.(string)
	// storagestrategyDescBucket is the schema descriptor for bucket field.
	storagestrategyDescBucket := storagestrategyFields[5].Descriptor()
	// storagestrategy.BucketValidator is a validator for the "bucket" field. It is called by the builders before save.
	storagestrategy.BucketValidator = storagestrategyDescBucket.Validators[0].(func(string) error)
	// storagestrategyDescAccessKey is the schema descriptor for access_key field.
	storagestrategyDescAccessKey := storagestrategyFields[6].Descriptor()
	// storagestrategy.DefaultAccessKey holds the default value on creation for the access_key field.
	storagestrategy.DefaultAccessKey = storagestrategyDescAccessKey.Default.(string)
	// storagestrategyDescSecretKey is the schema descriptor for secret_key field.
	storagestrategyDescSecretKey := storagestrategyFields[7].Descriptor()
	// storagestrategy.DefaultSecretKey holds the default value on creation for the secret_key field.
	storagestrategy.DefaultSecretKey = storagestrategyDescSecretKey.Default.(string)
	// storagestrategyDescBasePath is the schema descriptor for base_path field.
	storagestrategyDescBasePath := storagestrategyFields[8].Descriptor()
	// storagestrategy.DefaultBasePath holds the default value on creation for the base_path field.
	storagestrategy.DefaultBasePath = storagestrategyDescBasePath.Default.(string)
	// storagestrategyDescDomain is the schema descriptor for domain field.
	storagestrategyDescDomain := storagestrategyFields[9].Descriptor()
	// storagestrategy.DefaultDomain holds the default value on creation for the domain field.
	storagestrategy.DefaultDomain = storagestrategyDescDomain.Default.(string)
	// storagestrategyDescMaster is the schema descriptor for master field.
	storagestrategyDescMaster := storagestrategyFields[10].Descriptor()
	// storagestrategy.DefaultMaster holds the default value on creation for the master field.
	storagestrategy.DefaultMaster = storagestrategyDescMaster.Default.(bool)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[1].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescPhoneNumber is the schema descriptor for phone_number field.
	userDescPhoneNumber := userFields[3].Descriptor()
	// user.PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	user.PhoneNumberValidator = userDescPhoneNumber.Validators[0].(func(string) error)
	// userDescPhoneNumberVerified is the schema descriptor for phone_number_verified field.
	userDescPhoneNumberVerified := userFields[4].Descriptor()
	// user.DefaultPhoneNumberVerified holds the default value on creation for the phone_number_verified field.
	user.DefaultPhoneNumberVerified = userDescPhoneNumberVerified.Default.(bool)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[5].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = func() func(string) error {
		validators := userDescPassword.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password string) error {
			for _, fn := range fns {
				if err := fn(password); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	webhookMixin := schema.WebHook{}.Mixin()
	webhookMixinFields0 := webhookMixin[0].Fields()
	_ = webhookMixinFields0
	webhookFields := schema.WebHook{}.Fields()
	_ = webhookFields
	// webhookDescCreatedAt is the schema descriptor for created_at field.
	webhookDescCreatedAt := webhookMixinFields0[1].Descriptor()
	// webhook.DefaultCreatedAt holds the default value on creation for the created_at field.
	webhook.DefaultCreatedAt = webhookDescCreatedAt.Default.(func() time.Time)
	// webhookDescUpdatedAt is the schema descriptor for updated_at field.
	webhookDescUpdatedAt := webhookMixinFields0[2].Descriptor()
	// webhook.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	webhook.DefaultUpdatedAt = webhookDescUpdatedAt.Default.(func() time.Time)
	// webhook.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	webhook.UpdateDefaultUpdatedAt = webhookDescUpdatedAt.UpdateDefault.(func() time.Time)
	// webhookDescName is the schema descriptor for name field.
	webhookDescName := webhookFields[0].Descriptor()
	// webhook.NameValidator is a validator for the "name" field. It is called by the builders before save.
	webhook.NameValidator = func() func(string) error {
		validators := webhookDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// webhookDescURL is the schema descriptor for url field.
	webhookDescURL := webhookFields[1].Descriptor()
	// webhook.URLValidator is a validator for the "url" field. It is called by the builders before save.
	webhook.URLValidator = func() func(string) error {
		validators := webhookDescURL.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(url string) error {
			for _, fn := range fns {
				if err := fn(url); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// webhookDescEvent is the schema descriptor for event field.
	webhookDescEvent := webhookFields[2].Descriptor()
	// webhook.EventValidator is a validator for the "event" field. It is called by the builders before save.
	webhook.EventValidator = func() func(string) error {
		validators := webhookDescEvent.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(event string) error {
			for _, fn := range fns {
				if err := fn(event); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
