// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gobee/ent/predicate"
	"gobee/ent/schedulejob"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScheduleJobUpdate is the builder for updating ScheduleJob entities.
type ScheduleJobUpdate struct {
	config
	hooks    []Hook
	mutation *ScheduleJobMutation
}

// Where appends a list predicates to the ScheduleJobUpdate builder.
func (_u *ScheduleJobUpdate) Where(ps ...predicate.ScheduleJob) *ScheduleJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScheduleJobUpdate) SetUpdatedAt(v time.Time) *ScheduleJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ScheduleJobUpdate) SetName(v string) *ScheduleJobUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScheduleJobUpdate) SetNillableName(v *string) *ScheduleJobUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the ScheduleJobMutation object of the builder.
func (_u *ScheduleJobUpdate) Mutation() *ScheduleJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScheduleJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScheduleJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScheduleJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schedulejob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ScheduleJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(schedulejob.Table, schedulejob.Columns, sqlgraph.NewFieldSpec(schedulejob.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schedulejob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(schedulejob.FieldName, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedulejob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScheduleJobUpdateOne is the builder for updating a single ScheduleJob entity.
type ScheduleJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScheduleJobMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScheduleJobUpdateOne) SetUpdatedAt(v time.Time) *ScheduleJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ScheduleJobUpdateOne) SetName(v string) *ScheduleJobUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScheduleJobUpdateOne) SetNillableName(v *string) *ScheduleJobUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the ScheduleJobMutation object of the builder.
func (_u *ScheduleJobUpdateOne) Mutation() *ScheduleJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the ScheduleJobUpdate builder.
func (_u *ScheduleJobUpdateOne) Where(ps ...predicate.ScheduleJob) *ScheduleJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScheduleJobUpdateOne) Select(field string, fields ...string) *ScheduleJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScheduleJob entity.
func (_u *ScheduleJobUpdateOne) Save(ctx context.Context) (*ScheduleJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleJobUpdateOne) SaveX(ctx context.Context) *ScheduleJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScheduleJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScheduleJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schedulejob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ScheduleJobUpdateOne) sqlSave(ctx context.Context) (_node *ScheduleJob, err error) {
	_spec := sqlgraph.NewUpdateSpec(schedulejob.Table, schedulejob.Columns, sqlgraph.NewFieldSpec(schedulejob.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScheduleJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schedulejob.FieldID)
		for _, f := range fields {
			if !schedulejob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schedulejob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schedulejob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(schedulejob.FieldName, field.TypeString, value)
	}
	_node = &ScheduleJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedulejob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
