// Code generated by ent, DO NOT EDIT.

package albumphoto

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the albumphoto type in the database.
	Label = "album_photo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldImageURL holds the string denoting the image_url field in the database.
	FieldImageURL = "image_url"
	// FieldViewCount holds the string denoting the view_count field in the database.
	FieldViewCount = "view_count"
	// FieldAlbumID holds the string denoting the album_id field in the database.
	FieldAlbumID = "album_id"
	// Table holds the table name of the albumphoto in the database.
	Table = "album_photos"
)

// Columns holds all SQL columns for albumphoto fields.
var Columns = []string{
	FieldID,
	FieldImageURL,
	FieldViewCount,
	FieldAlbumID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultViewCount holds the default value on creation for the "view_count" field.
	DefaultViewCount int
)

// OrderOption defines the ordering options for the AlbumPhoto queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByImageURL orders the results by the image_url field.
func ByImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageURL, opts...).ToFunc()
}

// ByViewCount orders the results by the view_count field.
func ByViewCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewCount, opts...).ToFunc()
}

// ByAlbumID orders the results by the album_id field.
func ByAlbumID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlbumID, opts...).ToFunc()
}
