// Code generated by ent, DO NOT EDIT.

package albumphoto

import (
	"gobee/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEQ(FieldUpdatedAt, v))
}

// ImageURL applies equality check predicate on the "image_url" field. It's identical to ImageURLEQ.
func ImageURL(v string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEQ(FieldImageURL, v))
}

// ViewCount applies equality check predicate on the "view_count" field. It's identical to ViewCountEQ.
func ViewCount(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEQ(FieldViewCount, v))
}

// AlbumID applies equality check predicate on the "album_id" field. It's identical to AlbumIDEQ.
func AlbumID(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEQ(FieldAlbumID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldLTE(FieldUpdatedAt, v))
}

// ImageURLEQ applies the EQ predicate on the "image_url" field.
func ImageURLEQ(v string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEQ(FieldImageURL, v))
}

// ImageURLNEQ applies the NEQ predicate on the "image_url" field.
func ImageURLNEQ(v string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldNEQ(FieldImageURL, v))
}

// ImageURLIn applies the In predicate on the "image_url" field.
func ImageURLIn(vs ...string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldIn(FieldImageURL, vs...))
}

// ImageURLNotIn applies the NotIn predicate on the "image_url" field.
func ImageURLNotIn(vs ...string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldNotIn(FieldImageURL, vs...))
}

// ImageURLGT applies the GT predicate on the "image_url" field.
func ImageURLGT(v string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldGT(FieldImageURL, v))
}

// ImageURLGTE applies the GTE predicate on the "image_url" field.
func ImageURLGTE(v string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldGTE(FieldImageURL, v))
}

// ImageURLLT applies the LT predicate on the "image_url" field.
func ImageURLLT(v string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldLT(FieldImageURL, v))
}

// ImageURLLTE applies the LTE predicate on the "image_url" field.
func ImageURLLTE(v string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldLTE(FieldImageURL, v))
}

// ImageURLContains applies the Contains predicate on the "image_url" field.
func ImageURLContains(v string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldContains(FieldImageURL, v))
}

// ImageURLHasPrefix applies the HasPrefix predicate on the "image_url" field.
func ImageURLHasPrefix(v string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldHasPrefix(FieldImageURL, v))
}

// ImageURLHasSuffix applies the HasSuffix predicate on the "image_url" field.
func ImageURLHasSuffix(v string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldHasSuffix(FieldImageURL, v))
}

// ImageURLEqualFold applies the EqualFold predicate on the "image_url" field.
func ImageURLEqualFold(v string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEqualFold(FieldImageURL, v))
}

// ImageURLContainsFold applies the ContainsFold predicate on the "image_url" field.
func ImageURLContainsFold(v string) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldContainsFold(FieldImageURL, v))
}

// ViewCountEQ applies the EQ predicate on the "view_count" field.
func ViewCountEQ(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEQ(FieldViewCount, v))
}

// ViewCountNEQ applies the NEQ predicate on the "view_count" field.
func ViewCountNEQ(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldNEQ(FieldViewCount, v))
}

// ViewCountIn applies the In predicate on the "view_count" field.
func ViewCountIn(vs ...int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldIn(FieldViewCount, vs...))
}

// ViewCountNotIn applies the NotIn predicate on the "view_count" field.
func ViewCountNotIn(vs ...int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldNotIn(FieldViewCount, vs...))
}

// ViewCountGT applies the GT predicate on the "view_count" field.
func ViewCountGT(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldGT(FieldViewCount, v))
}

// ViewCountGTE applies the GTE predicate on the "view_count" field.
func ViewCountGTE(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldGTE(FieldViewCount, v))
}

// ViewCountLT applies the LT predicate on the "view_count" field.
func ViewCountLT(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldLT(FieldViewCount, v))
}

// ViewCountLTE applies the LTE predicate on the "view_count" field.
func ViewCountLTE(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldLTE(FieldViewCount, v))
}

// AlbumIDEQ applies the EQ predicate on the "album_id" field.
func AlbumIDEQ(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldEQ(FieldAlbumID, v))
}

// AlbumIDNEQ applies the NEQ predicate on the "album_id" field.
func AlbumIDNEQ(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldNEQ(FieldAlbumID, v))
}

// AlbumIDIn applies the In predicate on the "album_id" field.
func AlbumIDIn(vs ...int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldIn(FieldAlbumID, vs...))
}

// AlbumIDNotIn applies the NotIn predicate on the "album_id" field.
func AlbumIDNotIn(vs ...int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldNotIn(FieldAlbumID, vs...))
}

// AlbumIDGT applies the GT predicate on the "album_id" field.
func AlbumIDGT(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldGT(FieldAlbumID, v))
}

// AlbumIDGTE applies the GTE predicate on the "album_id" field.
func AlbumIDGTE(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldGTE(FieldAlbumID, v))
}

// AlbumIDLT applies the LT predicate on the "album_id" field.
func AlbumIDLT(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldLT(FieldAlbumID, v))
}

// AlbumIDLTE applies the LTE predicate on the "album_id" field.
func AlbumIDLTE(v int) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.FieldLTE(FieldAlbumID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AlbumPhoto) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AlbumPhoto) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AlbumPhoto) predicate.AlbumPhoto {
	return predicate.AlbumPhoto(sql.NotPredicates(p))
}
