// Code generated by ent, DO NOT EDIT.

package license

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the license type in the database.
	Label = "license"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldMachineCode holds the string denoting the machine_code field in the database.
	FieldMachineCode = "machine_code"
	// FieldLicenseKey holds the string denoting the license_key field in the database.
	FieldLicenseKey = "license_key"
	// FieldCustomerName holds the string denoting the customer_name field in the database.
	FieldCustomerName = "customer_name"
	// FieldExpireDate holds the string denoting the expire_date field in the database.
	FieldExpireDate = "expire_date"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the license in the database.
	Table = "licenses"
)

// Columns holds all SQL columns for license fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldMachineCode,
	FieldLicenseKey,
	FieldCustomerName,
	FieldExpireDate,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// MachineCodeValidator is a validator for the "machine_code" field. It is called by the builders before save.
	MachineCodeValidator func(string) error
	// LicenseKeyValidator is a validator for the "license_key" field. It is called by the builders before save.
	LicenseKeyValidator func(string) error
	// CustomerNameValidator is a validator for the "customer_name" field. It is called by the builders before save.
	CustomerNameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int
)

// OrderOption defines the ordering options for the License queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMachineCode orders the results by the machine_code field.
func ByMachineCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMachineCode, opts...).ToFunc()
}

// ByLicenseKey orders the results by the license_key field.
func ByLicenseKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicenseKey, opts...).ToFunc()
}

// ByCustomerName orders the results by the customer_name field.
func ByCustomerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerName, opts...).ToFunc()
}

// ByExpireDate orders the results by the expire_date field.
func ByExpireDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpireDate, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
