// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ModelSchema is the predicate function for modelschema builders.
type ModelSchema func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
