// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Album is the predicate function for album builders.
type Album func(*sql.Selector)

// AlbumPhoto is the predicate function for albumphoto builders.
type AlbumPhoto func(*sql.Selector)

// ApiPerms is the predicate function for apiperms builders.
type ApiPerms func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Essay is the predicate function for essay builders.
type Essay func(*sql.Selector)

// FLink is the predicate function for flink builders.
type FLink func(*sql.Selector)

// FLinkGroup is the predicate function for flinkgroup builders.
type FLinkGroup func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// FriendCircleRecord is the predicate function for friendcirclerecord builders.
type FriendCircleRecord func(*sql.Selector)

// FriendCircleRule is the predicate function for friendcirclerule builders.
type FriendCircleRule func(*sql.Selector)

// ModelSchema is the predicate function for modelschema builders.
type ModelSchema func(*sql.Selector)

// Oauth2AccessToken is the predicate function for oauth2accesstoken builders.
type Oauth2AccessToken func(*sql.Selector)

// Oauth2Code is the predicate function for oauth2code builders.
type Oauth2Code func(*sql.Selector)

// Oauth2RefreshToken is the predicate function for oauth2refreshtoken builders.
type Oauth2RefreshToken func(*sql.Selector)

// Page is the predicate function for page builders.
type Page func(*sql.Selector)

// PayChannel is the predicate function for paychannel builders.
type PayChannel func(*sql.Selector)

// PayOrder is the predicate function for payorder builders.
type PayOrder func(*sql.Selector)

// PersonalAccessToken is the predicate function for personalaccesstoken builders.
type PersonalAccessToken func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// ScheduleJob is the predicate function for schedulejob builders.
type ScheduleJob func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// StorageStrategy is the predicate function for storagestrategy builders.
type StorageStrategy func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// VisitLog is the predicate function for visitlog builders.
type VisitLog func(*sql.Selector)

// WebHook is the predicate function for webhook builders.
type WebHook func(*sql.Selector)
